### ISSUE TITLE
Asset Path while Publishing to Github Pages

### ISSUE THREAD

**Issue by ramnathv** [ruhoh/ruhoh.rb#100]
This issue might have been already resolved in one of the issues, but I was unable to find a clean answer and hence the reason for posting this. The example I have is reproducible. Here is what I did

```
ruhoh new myblog
cd myblog
ruhoh compile
cd compiled
git init .
touch .nojekyll
git add .
git commit -m 'update myblog'
git push git@github.com:ramnathv/testbook.git master:gh-pages --force
git rm -rf .git
cd ..
```

Basically, I generate a ruhoh blog locally, push the compiled directory to the root of a gh-pages branch (using force) and then removing the .git directory since I don't want to be tracking generated files.

Now everything works, except that the paths in `index.html` are being resolved with respect to `http://ramnathv.github.com` and not with respect to `http://ramnathv.github.com/testbook`.

I remember having seen this issue about gh-pages in a different context, but I am unable to recall the specifics. I would really appreciate if anyone could point me to a clean way of making this work.

**Comment by plusjade** [comment]
Have you tried setting the `base_path` config variable?

Sorry I don't think this is covered in the official docs site but is available in the latest updates feed: http://ruhoh.com/blog/releases/ruhoh-version-1-0#toc_4 

For your example, hosting on http://ramnathv.github.com/testbook

``` yaml
# config.yml

base_path: "/testbook"
```

**Comment by ramnathv** [comment]
Yes that works. The only modification I had to make is that I had to switch into `compiled/testbook` and then do the git dance to push my blog.
