### ISSUE TITLE
USERNAME.ruhoh.com doesn't update when making commit to private GitHub repo

### ISSUE THREAD

**Issue by amorphid** [ruhoh/ruhoh.rb#101]
I created a private repo and couldn't deploy to USERNAME.ruhoh.com.  After making the repo public, I still couldn't deploy.  However, after creating a virgin public repo and pushing to that (sounds wrong), the deploy to USERNAME.ruhoh.com.

TL;DR -- deploy to private repo doesn't seem to work.

**Comment by plusjade** [comment]
Haha, that's funny! 

post.ruhoh.com does not ask for read/write access on your private repos so it can only pull from public repos.

It would in fact, be a nice thing to support private repos though since post.ruhoh.com already asks for GitHub authentication, it's just a matter of asking for read/write. 

I take it you would want something like this?

**Comment by ramnathv** [comment]
I would use a `makefile` to automate deployment of private github repos. I got one working, so let me know if you need a `makefile`.

**Comment by amorphid** [comment]
I would private repo support, yes :).  However, I'm also exploring other
hosting options with a higher SLA, so don't kill yourself just to please
lil old me!

**Comment by brandonparsons** [comment]
@ramnathv Are you able to share your `makefile` with me?  I think it might be useful for what I'm working on.  `parsons dot brandon at gmail dot com`

Cheers!

**Comment by plusjade** [comment]
@ramnathv perhaps you can link to a public gist?

**Comment by ramnathv** [comment]
Here you go. https://gist.github.com/3890278

Let me know if you are having any trouble using this approach. I saw it online in a different context, and will add a reference.

**Comment by plusjade** [comment]
Supporting private repositories should be the job of post.ruhoh.com. I'm closing this and adding it to [post.ruhoh.com issues](https://github.com/ruhoh/post.ruhoh.com/issues/4). Thanks!
