### ISSUE TITLE
add other directories to the root of my website

### ISSUE THREAD

**Issue by YounesCheikh** [ruhoh/ruhoh.rb#104]
hi
i have a folder on the root of my website contains files that are linked by other websites 
the folder named portail_files on my  git repo: 

 [https://github.com/cyounes/cyounes.ruhoh.com/tree/master/portail_files](https://github.com/cyounes/cyounes.ruhoh.com/tree/master/portail_files) 

but when i try to access to files that contains: 
[http://cyounes.com/portail_files/boxman1.png](http://cyounes.com/portail_files/boxman1.png) 
i get this message error : 

<h1>404 Not Found</h1>

_how_ can i solve this **problem** ?
thanks.

**Comment by plusjade** [comment]
the root of the website is in /pages not on the root of the blog. 

ruhoh takes a white list approach, so the page folder namespace  is used to say "I want to serve these pages".
just drop your folder into pages and it should work.

**Comment by YounesCheikh** [comment]
The same problem, when i move the folder into /pages/ and try to start `rackup -p 9292` i get this error message: 

```
/var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/utils.rb:24:in `match': invalid byte sequence in UTF-8 (ArgumentError)
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/utils.rb:24:in `match'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/utils.rb:24:in `parse_page_file'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/parsers/pages.rb:16:in `block (2 levels) in generate'
        from /usr/lib/ruby/1.9.1/fileutils.rb:125:in `chdir'
        from /usr/lib/ruby/1.9.1/fileutils.rb:125:in `cd'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/parsers/pages.rb:16:in `block in generate'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/parsers/pages.rb:13:in `each'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/parsers/pages.rb:13:in `generate'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/db.rb:25:in `update'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/db.rb:44:in `block in update_all'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/db.rb:43:in `each'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/db.rb:43:in `update_all'
        from /var/lib/gems/1.9.1/gems/ruhoh-1.1/lib/ruhoh/program.rb:25:in `preview'
        from /home/cyounes/private/dev/ruhoh/cyounes.ruhoh.com/config.ru:4:in `block in <main>'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
        from /home/cyounes/private/dev/ruhoh/cyounes.ruhoh.com/config.ru:1:in `new'
        from /home/cyounes/private/dev/ruhoh/cyounes.ruhoh.com/config.ru:1:in `<main>'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in `eval'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in `parse_file'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:200:in `app'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:301:in `wrapped_app'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:252:in `start'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:137:in `start'
        from /var/lib/gems/1.9.1/gems/rack-1.4.1/bin/rackup:4:in `<top (required)>'
        from /usr/local/bin/rackup:23:in `load'
        from /usr/local/bin/rackup:23:in `<main>'
```

Also i tried to push the files to my [github repo](https://github.com/cyounes/cyounes.ruhoh.com/tree/master/pages)  and there were no changes on the [site](http://cyounes.com/portail_files/boxman1.png) :(

**Comment by YounesCheikh** [comment]
the same problem if want to upload the html file to validate my website on google webmaster :(  
[link](http://cyounes.com/google09632f5fdc088cac.html)

**Comment by plusjade** [comment]
This should now be fixed in ruhoh 2.x: https://github.com/ruhoh/ruhoh.rb/commit/7734a6aafb4d28c806c1169893354c290cadcec2

I'm assuming, based on the error, that ruhoh is expecting top YAML metadata for every page file. However it should still work without it. You'll still need to specify `layout:false` if you want to omit any layout rendering though.
