### ISSUE TITLE
Error on rackup? 

### ISSUE THREAD

**Issue by kyleroche** [ruhoh/ruhoh.rb#105]
Just installed today. Moving from Jekyll. Got this: 

Kyles-MacBook-Pro:kyleroche.ruhoh.com kyleroche$ rackup -p 9292
/Library/Ruby/Gems/1.8/gems/ruhoh-1.1/lib/ruhoh.rb:2: uninitialized constant Encoding (NameError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:60:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:60:in`require'
    from /Users/kyleroche/Documents/Development/kyleroche.ruhoh.com/config.ru:3
    from /Library/Ruby/Gems/1.8/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
    from /Library/Ruby/Gems/1.8/gems/rack-1.4.1/lib/rack/builder.rb:51:in`initialize'
    from /Users/kyleroche/Documents/Development/kyleroche.ruhoh.com/config.ru:1:in `new'
    from /Users/kyleroche/Documents/Development/kyleroche.ruhoh.com/config.ru:1

**Comment by plusjade** [comment]
Looks like you are using ruby 1.8.x. Can you run 1.9.x at all? ruhoh is built and tested on 1.9.x and does not officially suport 1.8.x =/

**Comment by plusjade** [comment]
Just saw you close it, did you get it fixed?

**Comment by kyleroche** [comment]
I did. Thanks. (new to ruby. i'm a scala guy) Great work, btw. I'm already
posting: kyleroche.ruhoh.com
