### ISSUE TITLE
Implementing Rack::Builder

### ISSUE THREAD

**Issue by ghost** [ruhoh/ruhoh.rb#106]
I'm trying to create a plugin that just adds REST routes/logic for a Backbone.js model inside a widget which binds data to a page. Since I didn't see a direct interface for this, I just modified config.ru.. I lose the assets when I do this:

``` ruby
require 'rack'
require 'ruhoh'

# run Ruhoh::Program.preview

custom = Rack::Builder.new do
  use Rack::CommonLogger
  map '/' do
    run Ruhoh::Program.preview
  end

  # WILL BE JSON
  map '/model' do
    run Proc.new {|env| [200, {"Content-Type" => "text/html"},  StringIO.new("JSON")] }
  end
end

run custom
```

What do you think is a good way to go about this?

**Comment by plusjade** [comment]
This is what `Ruhoh::Program.preview` does: https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/program.rb#L14-51

You are probably better off copy/pasting the above logic into your config.ru file and then adding in your custom logic. 

The problem with your specific example code is that rack works from the top to the bottom. So if you have `map '/'` first, then it will always match and never get to `map '/model'`

So you might try: (note this is untested)

``` ruby
#config.ru

Ruhoh.setup
Ruhoh.config.env = 'development'
Ruhoh.setup_paths
Ruhoh.setup_urls
Ruhoh.setup_plugins

Ruhoh::DB.update_all

Ruhoh::Watch.start
Rack::Builder.new {
  use Rack::Lint
  use Rack::ShowExceptions

  # WILL BE JSON
  map '/model' do
    run Proc.new {|env| [200, {"Content-Type" => "text/html"},  StringIO.new("JSON")] }
  end

  # Serve base media
  map Ruhoh.urls.media do
    run Rack::File.new(Ruhoh.paths.media)
  end

  # Serve theme assets
  map Ruhoh.urls.theme do
    run Rack::File.new(Ruhoh.paths.theme)
  end

  # Serve widget javascripts
  map Ruhoh.urls.widgets do
    run Rack::File.new(Ruhoh.paths.widgets)
  end

  map '/' do
    run Ruhoh::Previewer.new(Ruhoh::Page.new)
  end
}

```

**Comment by plusjade** [comment]
This above is ruhoh 1.x code

ruhoh 2.0.alpha program for rack builder is here: https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/programs/preview.rb
