### ISSUE TITLE
Markdown tables? 

### ISSUE THREAD

**Issue by kyleroche** [ruhoh/ruhoh.rb#107]
I can't seem to get markdown table formatting to work. Is there a different syntax guide for what is supported? For example, this won't render for me in a post: 

| First Header | Second Header |
| --- | --- |
| Row1 Cell1 | Row1 Cell2 |
| Row2 Cell1 | Row2 Cell2 |

**Comment by YounesCheikh** [comment]
I have the same problem :tractor:

**Comment by binaryphile** [comment]
The default markdown parser doesn't support table syntax, but kramdown does.  The docs include directions on how to enable kramdown parsing.

**Comment by plusjade** [comment]
Link to relevant documentation: http://ruhoh.com/docs/2/plugins/#toc_7

Support for kramdown as of ruhoh 2.x

``` ruby
class Ruhoh
  module Converter
    module Markdown
      def self.extensions
        ['.md', '.markdown']
      end
      def self.convert(content)
        require 'kramdown'
        Kramdown::Document.new(content).to_html
      end
    end
  end
end
```

Make sure the kramdown gem is in your bundle or local gemset.
