### ISSUE TITLE
mapping subdomain to Github Group

### ISSUE THREAD

**Issue by kyleroche** [ruhoh/ruhoh.rb#108]
Hi, my personal site works fine. I am a member of a github team, however. http://post.ruhoh.com doesn't seem to allow the option to map my team's site to Ruhoh. 

Do I need to make a second github account just for this purpose? 

Thanks!

**Comment by dvogeldev** [comment]
I too am unable to publish to http://USERNAME.ruhoh.com
I've set the webhook to post@ruhoh.com as did @kyleroche I receive an error message from USERNAME.ruhoh.com/log.txt "ERROR: Could not update Git repository"

**Comment by plusjade** [comment]
Moving to [post.ruhoh.com issues](https://github.com/ruhoh/post.ruhoh.com/issues/5)
