### ISSUE TITLE
Default mobile-friendly view?

### ISSUE THREAD

**Issue by jamshid** [ruhoh/ruhoh.rb#114]
The default style is hard to read on a mobile -- the text is small, and it doesn't display nicely like most sites do today. Seems a blog has to be mobile friendly by default. Does someone just need to create a mobile theme or modify the existing layout?

**Comment by karfau** [comment]
have you tried if the [hooligan-theme](https://github.com/ruhoh/hooligan) works better "on a mobile"?

**Comment by plusjade** [comment]
@jamshid @karfau sorry for the late reply but I wanted to actually, you know, deliver a solution!

I've updated the default 2.0.alpha blog with a new, minimal/clean fully responsive theme based on twitter bootstrap 2.2.2
 https://github.com/ruhoh/blog/tree/2.0.alpha

No preview of it yet but Jonathon Kram already customized it for himself here: http://www.jdkram.net/
