### ISSUE TITLE
Privacy issue

### ISSUE THREAD

**Issue by torrentkino** [ruhoh/ruhoh.rb#115]
Hello,

I tried ruroh. There are many things I like, but I also have some issues with the default theme. Disabling Google Analytics and Disqus worked for me so far. But I had no luck with disabling Google Prettify. My webbrowser tries to contact the Cloudflare CDN every time I visit my test page. That is not a desired behavior for an intranet page. And sending the "Referer:" header to a third party might not be a desired behavior as well.

Kind regards,
Aiko

**Comment by karfau** [comment]
I managed to get rid of google_prettify by removing the following line:
https://github.com/ruhoh/twitter/blob/master/layouts/default.html#L58
from theme/twitter/layouts/default.html with the content

```
{{{ google_prettify }}}
```

if you would like to keep google_prettify without loading the js-file from the cdn you could provide another layout in widgets/google_prettify/layouts/[your_layout_name].html
which could be a custumized version of 
https://github.com/ruhoh/ruhoh.rb/blob/master/system/widgets/google_prettify/layouts/google_prettify.html
if you name this layout something different then google_prettify.html you need to configure the widget in 
widgets/google_prettify/config.yml
adding the line 

```
layout : \[your_layout_name]
```

(I would expect a google_prettify.html in the layouts-folder to overwrite the systemwide, but havn't tested it.)

I hope that helps :)

**Comment by plusjade** [comment]
Thanks @torrentkino for pointing out a legitimate problem. I know this took forever but we did address this issue!

CDN path is now optional thanks to @caspervonb https://github.com/ruhoh/ruhoh.rb/commit/c6f1a38fbd614bb0efd22806aa99515fe86ca95d , https://github.com/ruhoh/ruhoh.rb/commit/2251fec384ea62cde160a0b2646440dea027eecb

**since 2.2**
