### ISSUE TITLE
ruhoh 2.0 bundle install error

### ISSUE THREAD

**Issue by jacobmgreer** [ruhoh/ruhoh.rb#117]
The bundle install error is:

"The path /Users/jade/Dropbox/gems/ruhoh does not exist."

where is the typical path for this? i see it in the gemfile

**Comment by jacobmgreer** [comment]
Ok, so i got it to work. I download this as a zip and put it into the gem folder. Then changed the path to that location. It worked! :D

**Comment by plusjade** [comment]
Oops, `/Users/jade/Dropbox/gems/ruhoh` is my local path I use to run my development gem.

It should be:

```
gem 'ruhoh', :git => 'git://github.com/ruhoh/ruhoh.rb.git' 
```

https://github.com/ruhoh/blog/commit/6ff797a613c241a94d857533b1b901c533da8e4d

=x

**Comment by jacobmgreer** [comment]
:+1:
