### ISSUE TITLE
ruhoh 2.0: create new theme

### ISSUE THREAD

**Issue by jacobmgreer** [ruhoh/ruhoh.rb#118]
bundle exec ruhoh theme "pizza"

is:

WARNING: Nokogiri was built against LibXML version 2.7.3, but has dynamically loaded 2.7.8
/Library/Ruby/Gems/1.8/gems/ruhoh-2.0/lib/ruhoh/resources_interface.rb:39:in `const_get': uninitialized constant Ruhoh::Resources::Theme::Client (NameError)
    from /Library/Ruby/Gems/1.8/gems/ruhoh-2.0/lib/ruhoh/resources_interface.rb:39:in`block (2 levels) in class:ResourcesInterface'
    from /Library/Ruby/Gems/1.8/gems/ruhoh-2.0/lib/ruhoh/client.rb:40:in `initialize'
    from /Library/Ruby/Gems/1.8/gems/ruhoh-2.0/bin/ruhoh:34:in`new'
    from /Library/Ruby/Gems/1.8/gems/ruhoh-2.0/bin/ruhoh:34:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/bin/ruhoh:23:in`load'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/bin/ruhoh:23:in `<main>'

**Comment by plusjade** [comment]
I took out the theme scaffold as I kept forgetting to update the scaffold as the API changed. I can add it back in if there's a need.

In any case, the command is wrong. All client commands are namespaced by their resource. So any command having to do with "themes" resource would be `ruhoh themes some-command some-arg`

In this case (though this doesn't exist):

```
$ bundle exec ruhoh themes new "pizza"
```

**Comment by jacobmgreer** [comment]
it's not really needed, it's probably more practical to make it in finder (which i did after the error)

**Comment by plusjade** [comment]
What is finder?

**Comment by jacobmgreer** [comment]
:D this thing outside of terminal on a mac.

**Comment by karfau** [comment]
Well, the docs @ http://ruhoh.com/docs/2/themes/#toc_16 states

> The Ruhoh command-line client can automatically create scaffolding for building a new theme.
> 
> ```
> $ ruhoh theme 'new-theme-name'
> ```

but neither this (prepended with ´´´bundle exec´´´) nor 

```
bundle exec ruhoh themes new "pizza"
```

works:
So it would be nice to either update the documentation (could as well be a 'work in progress, use your favorite tool to customize the existing one'-message)
or leave this bug open.

thx

**Comment by martasd** [comment]
It would be useful to document that 

```
$ ruhoh theme 'new-theme-name'
```

is deprecated. And yes, I would find it useful as a beginner to help me get started.
