### ISSUE TITLE
ruhoh 2.0 templating issues

### ISSUE THREAD

**Issue by jacobmgreer** [ruhoh/ruhoh.rb#119]
the rumored {{posts.categories.all.count}} doesn't seem to be working

also {{urls.theme_media}} isn't making a url

**Comment by jacobmgreer** [comment]
figured out the counting problem

but still the urls.theme_media problem

**Comment by jacobmgreer** [comment]
additionally, is markdown rendering in .md files outside of posts folder?

**Comment by jacobmgreer** [comment]
another template issue with layouts.

layout specified in post doesn't seem to be selecting specified layout.

**Comment by plusjade** [comment]
> but still the urls.theme_media problem

`urls.theme_media` is deprecated in favor of just using `urls.theme` and drilling into the arbitrary directory structure.

So you would do something like:

``` html
<img src="{{urls.theme}}/media/pic.jpg">
```

You can see all the available url paths by running console:

``` bash
$ bundle exec ruhoh c
> ruhoh.db.urls
 => {"base_path"=>"/", "dash"=>"/dash", "javascripts"=>"/assets/twitter/javascripts", "media"=>"/assets/media", "paginator"=>"/posts", "stylesheets"=>"/assets/twitter/stylesheets", "theme"=>"/assets/twitter", "widgets"=>"/assets/widgets"} 
```

> additionally, is markdown rendering in .md files outside of posts folder?

Which directory specifically? Note every directory is acting as a namespace for a given resource. So the resource implementation has total control over how the files inside that namespace behave.

> layout specified in post doesn't seem to be selecting specified layout.

Terrible regression on my part; fixed: https://github.com/ruhoh/ruhoh.rb/commit/a1330ceeac06fc7927269aafa6394364b0a67750

**Comment by jacobmgreer** [comment]
it's not doing markdown on a .md files in pages. also in a folder i made called "stamps" which rendered the markdown in ruhoh 1. is there documentation on making a new resource/namespace?

**Comment by jacobmgreer** [comment]
posts with a specified layout don't seem to be rendering markdown either.

**Comment by plusjade** [comment]
I'm downloading your blog and seeing if I can reproduce the errors.

With my personal setup I am able to parse markdown on pages and on posts with a custom layout. Can you post some relevant code or push what you have to GitHub so I can take a look? 

What is the exact output? Is it the raw contents of the file? Does it have HTML but it's jus not rendering it?

Also, are you rendering content with triple mustache syntax:

```
# in the post sub-layout
{{{page.content}}}
```

**Comment by jacobmgreer** [comment]
Ah, the triple mustache syntax was the problem! Success!
