### ISSUE TITLE
{{# categories }} and {{# tags }} give the same list

### ISSUE THREAD

**Issue by davejlong** [ruhoh/ruhoh.rb#12]
I have a categories.html and a tags.html page on my site. Here is the code for each of them
## Tags.html:

```
title: Blog Tags
description:

layout: page

---
<ul class="tag_box inline">
{{# tags }}
  <li>
    <a href="{{ url }}">{{ name.capitalize }} <span>{{ count }}</span></a>
  </li>
{{/ tags }}
</ul>


{{# tags }}
  <h2 id="{{name}}-ref">{{name.capitalize}}</h2>
  {{# posts?to_posts }}
    <li><a href="{{url}}">{{title}}</a></li>
  {{/ posts?to_posts }}
{{/ tags }}
```

Categories.html
    ---
    title: Blog Categories
    description:

```
layout: page

---
<ul class="tag_box inline">
{{# categories }}
  <li>
    <a href="{{ url }}">{{ name.capitalize }} <span>{{ count }}</span></a>
  </li>
{{/ categories }}
</ul>

{{# categories }}
  <h2>{{ name.capitalize }} ({{ count }})</h2>
  <ul>
    {{# posts?to_posts }}
      <li><a href="{{url}}">{{title}}</a></li>
    {{/ posts?to_posts }}
  </ul>
{{/ categories }}
```

Both pages only render categories onto the page. If I run `ruhoh payload` I can clearly see that there are tags and categories in my site:

```
"tags"=>
  {"Kony 2012"=>
    {"count"=>1,
     "name"=>"Kony 2012",
     "url"=>"/tags.html#Kony 2012-ref",
     "posts"=>["_posts/2012-03-15-kony-2012-campaign.md"]},
   "Uganda 2011 Trip"=>
    {"count"=>1,
     "name"=>"Uganda 2011 Trip",
     "url"=>"/tags.html#Uganda 2011 Trip-ref",
     "posts"=>["_posts/2011-11-08-bringing-computers-to-uganda.md"]},
   "Arduino"=>
    {"count"=>1,
     "name"=>"Arduino",
     "url"=>"/tags.html#Arduino-ref",
     "posts"=>["_posts/2011-08-15-how-to-use-arduinos-map-function.md"]}},
 "categories"=>
  {"uganda"=>
    {"count"=>2,
     "name"=>"uganda",
     "url"=>"/categories.html#uganda-ref",
     "posts"=>
      ["_posts/2012-03-15-kony-2012-campaign.md",
       "_posts/2011-11-08-bringing-computers-to-uganda.md"]},
   "development"=>
    {"count"=>1,
     "name"=>"development",
     "url"=>"/categories.html#development-ref",
     "posts"=>
      ["_posts/2011-08-15-how-to-use-arduinos-map-function.md"]}}}},
```

I'm assuming that it is something that I am not doing correctly, but I don't know what I am not doing correctly.

**Comment by plusjade** [comment]
@davejlong  HUGE oversight on my part. That's what I get for copy/pasting methods (and not keeping my tests in sync with development)

This is a great catch. You can see the problem here: https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/templaters/helpers.rb#L29

I'll push this fix asap. Also you might need to specify the gem version in the gem file as I push all these fixes (but you probably already know that). 

Thanks for your support and please do feel free to add any feature requests or usability issues to steer the project in this young stage.

**Comment by davejlong** [comment]
If I leave the gem version off, shouldn't it just update to the latest version of the gem?  I am still fairly new to Ruby (coming from a ColdFusion background), so forgive my lack of knowledge here.

**Comment by plusjade** [comment]
I think you are probably right, it will assume the latest version. Though it is _best practice_ to specify specific gem versions - essentially that is what is going on within the Gemfile.lock. I was mainly letting you know so that we both can be sure you are running v0.1.3 and so we can know whether or not the issue has been resolved.

**Comment by davejlong** [comment]
Okay. I can confirm that the issue was resolved (without specifying the Gem version). I'll probably leave off the version until I actually launch my site, which I would think is better practice so that I can have my site on the latest version until launch and then use a version that I know works and selectively upgrade after I test new versions. 

## 

David Long
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by plusjade** [comment]
Right, glad it worked for you! I think the hassle of gem versions starts to present itself when you are in a team environment with everyone pushing and pulling throughout the day, then differences between localhost/staging/production etc.  In any case thanks again and look forward to more input!

**Comment by davejlong** [comment]
Strangely enough I moved from my Mac to my Ubuntu netbook and the Gemfile without specifying the version required would only install version 0.1.0. So I guess it is best to specify the version desired. (Last comment, I swear)
