### ISSUE TITLE
Paginator should use root_page for first page in version 2.x

### ISSUE THREAD

**Issue by tlupfer** [ruhoh/ruhoh.rb#122]
Seems that it's ignoring the root_page setting and assuming '/' for the first page.

**Comment by tlupfer** [comment]
Nevermind. It hadn't reloaded the configuration file. It still seems like strange behavior to require an additional page for the first group of posts.

**Comment by plusjade** [comment]
@tlupfer definitely right. I fixed the problem highlighted by you as well some some others after I investigated more. You can take a look at commits from https://github.com/ruhoh/ruhoh.rb/commit/8e69a3363c9b49adb3e2ef77a99bc92169890e8e to  https://github.com/ruhoh/ruhoh.rb/commit/38c7c79e8ab5a64a0c465844e4d0c1edf837a8e6

The blog scaffold has been updated to not provide default 'root_page' in config.yml. Be sure to remove this setting from your blog as well. Now, by default, the paginator just renders page 1 as it would any other page. If you provide a root_page it will omit compiling page 1 and leave it up to your implementation.

To update the gem: delete Gemfile.lock then run bundle install again. (The reason for deleting is I am not updating the version number on every change so bundler will assume the version is current and not re-download the HEAD from github)

Thanks for this useful feedback!

**Comment by tlupfer** [comment]
@plusjade thanks for the follow-up. I'm really excited about the direction of this project. Your responsiveness and vision have made it pretty awesome thus far. Keep it up!
