### ISSUE TITLE
Best place to add new types of content? Within /pages or create a new root directory?

### ISSUE THREAD

**Issue by webmasterkai** [ruhoh/ruhoh.rb#126]
I've been using Ruhoh to build up some quick and easy sites. For small business sites it's a total win over using a CMS. As I get into building increasingly complicated sites I'm beginning to think about where I would add different types of content. Since you have "pages" and "posts" in different directories it would seem to imply they are different types of content. Where then would I put content for products, portfolio entries, or staff entries? Is it best to put these within pages? If so, why then should posts get its own directory?

Another thing I'm wrestling with is how to split the site into specific repositories. It's really simple to have themes in individual repositories, but what if we want the content in its own repo too? If content has more than one directory in the root are themes then sub-module of "content"? It feels a bit like putting a theme in the database.

I completely understand that this is likely outside the scope of a "Blogging Platform". However, I'm finding usefulness in Ruhoh and seeing opportunity beyond technical blogging. :-)

**Comment by bjornmeansbear** [comment]
Good question. I've also been curious about creating different “content types.” I understand the difference between Pages and Posts in ruhoh, but I do not understand how to make different “content types” within the posts. One way conceivably would be with categories/tags, and then filter a view accordingly — accept that I sort of need to use those already AS categories and tags for their regular purposes.

Anyway, it appears that on the surface this is a possibility, I just don't get how to do it. (for example, I want a “portfolio” content type and a “glossary” content type for a specific project, perhaps others.)

**Comment by webmasterkai** [comment]
## [Everything is a Resource](http://ruhoh.com/docs/2/#toc_2)

"You can read a more in-depth"...

**Comment by Aetherpoint** [comment]
I also ran into this since i'm looking to create "portfolio-casestudy entries" with Ruhoh. I tried that with post categories, and i'm having trouble using pagination along with category filtering (is this possible?). It would be awesome to be able to assign different types of post content and deliver them to their appropriate layout. I'm just not sure how to do this fro with documentation.

I don't mind posts as an extension of pages. In my mind, posts contain portable, written content and pages add context to that content. That would mean that different "content types" would be assigned through posts and "context types" through pages.

**Comment by plusjade** [comment]
@webmasterkai, @bjornmeansbear , @Aetherpoint 

I know this took forever but ruhoh 2.1 is finally released and the primary design change is to allow arbitrarily defined "page collections". In a nutshell, every top-level directory implicitly defines it's own "page collection" which is scoped and tracks things like tags, categories, and can be iterated and paginated. This allows you to define "essays" and "snippets", etc and track them just as you would "posts", "pages" and so forth.

You can read more about the design at http://ruhoh.com/docs/2/

**Comment by Aetherpoint** [comment]
Awesome, pumped to use this!
