### ISSUE TITLE
compile ignores base_path for media/ folder

### ISSUE THREAD

**Issue by mlippautz** [ruhoh/ruhoh.rb#127]
ruhoh seems to ignore base_path for the media/ folder in the latest version. The media folder under themes/<theme>/media is copied over correctly (with base_path prepended).

spec: 2.0.alpha
ruhoh.rb: 910e74a82e52ab7ed70e6aac6da84077b778f143

config.yml:

```
...
base_path: "/test"
```

Test:

```
rm Gemfile.lock
bundle install
bundle exec ruhoh compile
ls -l compiled/
total 0
drwxr-xr-x   3 user  staff  102 Jan 14 12:58 assets
drwxr-xr-x  13 user  staff  442 Jan 14 12:58 test
ls -l compiled/assets/
total 0
drwxr-xr-x  6 user  staff  204 Jan 14 12:58 media
```

**Comment by plusjade** [comment]
Good catch @zoidrr, thank you for helping me test this stuff.
