### ISSUE TITLE
post orders in a specific category

### ISSUE THREAD

**Issue by jacobmgreer** [ruhoh/ruhoh.rb#128]
I'm using category specific lists on my archive, but when i use the posts?to_posts, the order is all weird. seems to be alphabetical on my machine and not sure what's happening on trendsient.com/categories

I don't see a way to force reverse chronological, it may also just be a bug.

https://github.com/jacobmgreer/jacobmgreer.ruhoh.com/blob/master/pages/categories.html#L12

**Comment by plusjade** [comment]
`to_posts` converts an array of ids to their respective post objects; as such, what it is really working with is an Array of ids. The resultant order of the posts is the order of the array. The reason this has to be that way is in the case you have custom data, such as a navigation menu:

``` yaml
#data.yaml
navigation:
  - index.md
  - about.md
  - hi.md
```

```
{{data.navigation?to_pages}}
```

should preserve the order of the array.

To properly sort posts/pages objects I've implemented a `<=>` comparison operator internally that tells ruby to sort by chronological order when `sort`ing posts. All this means is that if you have an array of post objects, you can use ruby's native `.sort` to sort the array based on the previous logic.

Finally we remember that mustache allows you to call native methods on your objects:

``` html
{{# posts?to_posts.sort }}
      <div class="row-fluid">
          <div class="span9"><p><a href="{{url}}">{{title}}</a></p></div>
          <div class="span3 visible-desktop" align="right"><p><script type="text/javascript">document.write(moment("{{ date }}", "YYYY-MM-DD").fromNow());</script></p></div>
      </div>
{{/ posts?to_posts.sort }}
```

I faced the same problem during development and I'm very happy to have learned all this `<=>` stuff ; ruby is quite nice.

**Comment by karfau** [comment]
Are we losing contact to language-independent templates here?
maybe it would be more clear for the user if there would be another helper for this case, like 
`{{# posts?to_posts_sorted }}
...
`
just my 2 cents :-)

**Comment by jacobmgreer** [comment]
this has been a delightful crash course in understanding mustache and ruby. i'm hoping to understand enough to work on a ruhoh plugin soon :smile_cat:

**Comment by plusjade** [comment]
@karfau you are definitely right -- that is something I had not considered.I honestly don't have an answer right now.

While I do think it is important to be language agnostic, I realize it is pre-optimization for language implementations that don't exist yet. This will stick in the back of my mind, but I think for now I want to get the rubyists as happy as possible and then figure out how to take that _success_ to javascript and python and php, etc.

The key concern for me there is the _success_ part!

**Comment by karfau** [comment]
@plusjade That's a good point.

I'm no rubyist, but I'm happy to if this gets a success, and I like things that just work the way they do :)
