### ISSUE TITLE
problem with new ruhoh build?

### ISSUE THREAD

**Issue by jacobmgreer** [ruhoh/ruhoh.rb#129]
After updating to alpha3, this error is showing up when running

bundle exec rackup -p 9292

when i try to access the blog on localhost -->

NoMethodError: undefined method `mark_active_page' for #Ruhoh::Views::MasterView:0x007fe2edce9348

**Comment by plusjade** [comment]
Sorry about that; `mark_active_page` is no longer needed so I removed it. This update should do it: https://github.com/ruhoh/blog/commit/dfc8a66c8e864f175acbaa6c851eddab158c407d (you can update your end manually)
