### ISSUE TITLE
bundle exec ruhoh posts new "Some Title" doesn't set 'title: "Some Title"'

### ISSUE THREAD

**Issue by coolaj86** [ruhoh/ruhoh.rb#131]
'nuff said

**Comment by plusjade** [comment]
Omitting the title is intended behavior. Posts/pages that don't have a title use the filename for the title. Setting the title is meant to explicitly say "I am customizing my title." Now I have no idea if that is the _best_ way to go about it, but that's how it works now.

**Comment by coolaj86** [comment]
I see where you're coming from. I noticed the default title behavior coming from the filename, but I thought that was odd because:

```
# ambiguous letter's or letter s?
bundle exec ruhoh posts new "Sponsored by the letter s"

# ambiguous SimpleHTTPServer or Simplehttpserver?
bundle exec ruhoh posts new "using python's SimpleHTTPServer"

# ambiguous Ssh or SSH? Fun or FUN!
bundle exec ruhoh posts new "SSH makes remoting FUN!"
```

Intuitively I want to give it the title with capitalization and punctuation as I expect it to be, and then it is immediately lost and I am left with sadness in my heart as I have to type it out again.

**Comment by plusjade** [comment]
Haha, yeah a fair point. That makes sense. I suppose there's no harm in hard-coding the title. I'll add this to my development schedule.

**Comment by coolaj86** [comment]
I'd also like to argue that "permalink: /path/to/file.html" should be set at creation as well. Once my content is published I may want to go back and tweek the title for SEO, but I'll have shared it on twitter, g+, etc so I don't want the url changing on me because I forget.

I argue that the burden of memory should be place in the system, not the user.
