### ISSUE TITLE
neither `urls.production_url` nor `production_url` refer to `config.yml:production_url`

### ISSUE THREAD

**Issue by coolaj86** [ruhoh/ruhoh.rb#134]
Seeing that `{{urls.base_path}}` refers to `config.yml:base_path`, I would would expect `{{urls.production_url}}` to behave similarly, or at least `{{production_url}}`.

Neither seem to have worked when I tested just now.

**Comment by coolaj86** [comment]
`grep`ing around a bit in `ruhoh.rb` I thought I had found the goldmine with `{{ site.production_url }}`, but neither that nor `{{ config.production_url }}` worked.

https://www.google.com/search?q=ruhoh+"production_url"

stumped

**Comment by plusjade** [comment]
Yep, looks like that's my fault (for not having tests of course). There is currently no way to get production_url.
In ruhoh 1.0 the data was thrown into a `payload` object that mapped literally to a key/value hash of data e.g. site.production_url from the config.yml file. 

In ruhoh 2.0 there is no payload, everything is dynamically loaded via method calls, so I'll have to make a sensible wrapper for fetching all the data in config.yml. 

Additionally you are right -- makes pretty good sense to define `urls.production` (omitting the _url for consistency). I'll probably go that route.

**Comment by coolaj86** [comment]
Also, on the note of twitter cards, it would be useful to have a `page.tweet` that is `page.tweet || page.description || page.content[0, 140]`.

Twitter cards won't accept my application until I have the full url (so I'll just hack that in) and descriptions to my posts.

https://dev.twitter.com/docs/cards/preview

**Comment by plusjade** [comment]
This looks great. I had no idea about this. Little niceties like this can aid in spurring interest. Please let me know how far you get with your implementation so we can merge it in. This weekend I'm set on pushing  asset-packaging support via [sprockets](github.com/sstephenson/sprockets) which has been a long-time coming. I also just pushed a new default theme at https://github.com/ruhoh/blog/tree/2.0.alpha if your interested.

Keep in touch!

**Comment by coolaj86** [comment]
I have a pull request over on ruhoh/twitter for the meta tags.

https://github.com/ruhoh/twitter/pull/2
