### ISSUE TITLE
How to upgrade ruhoh 1.1 to 2.0.alpha.

### ISSUE THREAD

**Issue by zjhui** [ruhoh/ruhoh.rb#141]
I have set up the ruhoh with github pages, but the  version is 1.1, i want to upgrade it to 2.0.alpha. Then i follow the [2.0.alpha readme](https://github.com/ruhoh/blog/tree/2.0.alpha#readme), copy the [Gemfile](https://github.com/ruhoh/blog/blob/2.0.alpha/Gemfile) into my local blog directory and run bundle install.  
Then i find it has many differents between 1.1 and 2.0 like config.yml and many others. How can i upgrade to ruhoh to 2.0 smoothly?

**Comment by plusjade** [comment]
Hi @zjhui sorry I took so long to reply but I was holding off until I stablized the API. It seems that took a crazy long time but ruhoh 2.1 is finally here so I'll finally close out this issue: Upgrade docs can be found here: http://ruhoh.com/docs/2/upgrading/
