### ISSUE TITLE
TypeError: no implicit conversion of Date into String

### ISSUE THREAD

**Issue by tlupfer** [ruhoh/ruhoh.rb#153]
TypeError: no implicit conversion of Date into String
    /usr/local/rvm/gems/ruby-2.0.0-p195/gems/ruhoh-2.1/lib/ruhoh/base/model_view.rb:47:in `parse'

added "to_s" and it gets rid of the error, but not sure if it breaks anything else?

**Comment by tlupfer** [comment]
Slightly different error message with ruby 1.9.3

127.0.0.1 - - [21/May/2013 19:03:02] "GET /favicon.ico HTTP/1.1" 200 - 0.0169
TypeError: can't convert Date into String
    /usr/local/rvm/gems/ruby-1.9.3-p429/gems/ruhoh-2.1/lib/ruhoh/base/model_view.rb:47:in `parse'

**Comment by Stebalien** [comment]
Yaml is converting it to a date for you. The simplest workaround is to wrap all of your dates in quotes however, it would obviously be better if this were fixed in ruhoh itself.
