### ISSUE TITLE
NoMethodError: undefined method `with_index' 

### ISSUE THREAD

**Issue by tlupfer** [ruhoh/ruhoh.rb#154]
Get the following error when loading summary views:

NoMethodError: undefined method `with_index' for #<Array:0x007fbf9a423ea0>
    /usr/local/rvm/gems/ruby-2.0.0-p195/gems/ruhoh-2.1/lib/ruhoh/base/model_view.rb:117:in`summary'

Commented 117-122 and everything else works fine.

**Comment by tlupfer** [comment]
This one is exclusive to ruby 2.0.0. It doesn't happen with 1.9.3

**Comment by plusjade** [comment]
Yeah there was a pull request for that with an easy fix. I need to upgrade my xcode before I can install ruby 2.0 though =x  hmm i will do that right now!
