### ISSUE TITLE
incompatible character encodings

### ISSUE THREAD

**Issue by theaob** [ruhoh/ruhoh.rb#16]
Hi, I've been trying to use staticly generated pages for my personal blog but Turkish is my mother language and many static generators doesn't support special characters in my language.
I've had the same problem with ruhoh as well. I put special chars on a post title ("Türkçe Başlık Oluşturmak İmkansız Mı?"). Publishing removed special characters on the actual post file but links generated were simply same as the title. And Webrick threw this error :
Encoding::CompatibilityError at /t%C3%BCrk%C3%A7e-ba%C5%9Fl%C4%B1k-olu%C5%9Fturmak-%C4%B0mkans%C4%B1z-m%C4%B1%3F
incompatible character encodings: UTF-8 and ASCII-8BIT

I'm really looking forward for this problem to disappear. Keep up the good work!

**Comment by plusjade** [comment]
@theaob do you have any ideas how to support the special characters? I am not too familiar with it. I would like to officially support many languages so it would be helpful if you can point me in the right direction and/or offer some contributions. - thanks!

**Comment by theaob** [comment]
Well wordpress and blogger converts them to english equivalents (é to e for example). That way is better for page rank and recognition but removing those characters from the link is also an option

**Comment by plusjade** [comment]
Thanks, I will check those solutions out and see what I can do.

**Comment by plusjade** [comment]
@theaob it took a while but [ruhoh v.1.0.0.alpha](http://ruhoh.com/blog/releases/version-1-0-0-alpha/) should support international characters now. Let me know if this solves the problem.
