### ISSUE TITLE
2.1 Compile Times Slow

### ISSUE THREAD

**Issue by lynnfaraday** [ruhoh/ruhoh.rb#166]
I have the change in Issue #132 already, but my compile time (for 766 posts) is still over 4 (or sometimes 5) minutes.  

195.950000  10.210000 206.160000 (253.937364)

Just looking at the output, it seems to be zipping along until it hits the pagination, and then it slows to a crawl. 

I understand that a large blog is never going to compile in a heartbeat, but this seems excessive.

Perhaps some improved caching or a way to say "compile only (this new post)" (plus of course the pagination) would help?

**Comment by plusjade** [comment]
This is fixed in 2.1.1 (https://github.com/ruhoh/ruhoh.rb/commit/536a38cde9e7da833b9ba6efd895bae20216fdf8) which is not yet on rubygems but can be installed via changing the Gemfile entry to:

``` ruby
gem 'ruhoh', git: 'git@github.com:ruhoh/ruhoh.rb.git'
```

I wil push the updated gem later tonight as I'll try to get more stuff in.

**Comment by plusjade** [comment]
@lynnfaraday sorry I realize you mentioned you already were running the fix! Reopened.

**Comment by lynnfaraday** [comment]
@Stebalien  - That cut my compile times down dramatically too.  Thanks!

Before:  230.770000  11.500000 242.270000 (262.423551)
After:   87.960000   6.440000  94.400000 ( 98.624152)
