### ISSUE TITLE
Plugin Architecture

### ISSUE THREAD

**Issue by davejlong** [ruhoh/ruhoh.rb#17]
One of the things that I really likes about Jekyll that I am missing with Ruhoh is a plugin architecture to make extending Ruhoh easier than creating a custom fork of the core. Especially when it comes to a generator architecture so that we could use CoffeeScript, SASS or Less for our assets without have to compile those outside of just using the compile command or uploading the code to GitHub.

**Comment by plusjade** [comment]
@davejlong I fully agree and plugins will be supported "natively" in the sense that ruhoh is built in a modular way, which is to say all modules are essentially plugins in themselves. I know that is quite vague and doesn't really give you any practical advice but I want to convey that I built ruhoh with the intention that it should be highly extensible in very intuitive way. 

With that said I have no documentation for it so please stay tuned! I'll update this thread specifically when I get some docs up.

EDIT: It would help me a lot if you can give me one concrete, specific use case that I can use as a prime example of a common plugin expectation. For example "I want to automatically compile less stylesheets in x directory and output to y directory (or however less works)

**Comment by davejlong** [comment]
Awesome I figured it was planned, but just trying to get to the 1.0
release.

sent from my Android smart phone
On Apr 22, 2012 4:04 PM, "Jade" <
reply@reply.github.com>
wrote:

**Comment by plusjade** [comment]
@davejlong just released plugin architecture in version 0.3.0, please let me know your feedback!

http://ruhoh.com/blog/releases/version-030/

**Comment by orva** [comment]
Plugins might have gem dependencies, automating bundler calls for plugin subdirs would be nice.

**Comment by plusjade** [comment]
@orva good idea but I'm not familiar with how to implement your suggestion. Can you give me an example?

**Comment by rriemann** [comment]
I think that [chiliproject](http://github.com/chiliproject/chiliproject) does something like this (or maybe rails in general).

Plug-Ins are saved in rails_root/vendor/plugins.

Example plugin which adds additional dependencies for bundler: http://github.com/ericpaulbishop/redmine_git_hosting

It would be cool to handle all these dependencies with bundler!

**Comment by rriemann** [comment]
The question was: Accept additional dependencies (nokogiri) for additional (core?) features (rss)?

When starting using ruhoh I don't want to pull a lot of custom code into my project. On the other side I like the Idea of not having a lot of dependencies.

So I suggest to create a bundle of additional gems like ruhoh-plugin-rss, which would have to be mentioned in the Gemfile and loaded automatically while compilation.

Maybe these gems would require also additional plug-ins like ruhoh-plugin-image-converter for ruhoh-plugin-image-thumbnailer.

When starting with templating I dont't want to use plain css, js and html nowadays. I expect each blogging system to support multiple formatters like kramdown, haml, coffescript, sass, less etc.

Following the idea of (one plugin) = (one gem), it would be possible without adding unnecessary dependencies.

**Comment by rriemann** [comment]
http://github.com/middleman/middleman is going to support http://github.com/sstephenson/sprockets for asset preprocessing in the next release. It would be nice to have such a support, too.

**Comment by plusjade** [comment]
Closing plugin issue, moving gem dependency discussion here: https://github.com/ruhoh/ruhoh.rb/issues/26
