### ISSUE TITLE
Widgets mess up pagination output when included in posts

### ISSUE THREAD

**Issue by lynnfaraday** [ruhoh/ruhoh.rb#171]
This appears to have been caused by [widget context change](https://github.com/ruhoh/ruhoh.rb/commit/c564232adec56a36a32f723e46dd8b5d48af2126), because if I revert that commit - everything's fine.

Is there something I'm doing wrong, or does the master render cause this somehow?

Sample post:

```
 Para1

 {{{widgets.foo}}}

 Para2
```

Sample widget (default.html):

```
 TEST1
 TEST2
 TEST3
```

Actual output **in pagination view**:

```
Para1

TEST1 TEST2 TEST3
```

Paragraph2 is lost!   Again, this is only in the index page view.  The full post is fine.

If I change the post to put the widget at the end:

```
 Para1

 Para2

 {{{widgets.foo}}}
```

Output:

```
 Para1

 Para2

 TEST1 TEST2
```

Now the last part of the widget output is lost.

Weird!

**Comment by lynnfaraday** [comment]
I patched this in my own fork by reverting the widget context change and making an alternate way for widgets to access the post data.  I'm pretty sure it's not the most "correct" way of doing it (hence why there's no pull request), but it will at least fix the widgets in the mean time.  [Commit](https://github.com/lynnfaraday/ruhoh.rb/commit/c50af972be0ed2adc3a2824c276b615b820ccafe)

**Comment by plusjade** [comment]
Are you sure this is not just the `post.summary` giving you a truncated version of the full post? If this is the case, https://github.com/ruhoh/ruhoh.rb/pull/170 by @stebalien provides a more customized summary generator which you can use to make sure the widget gets included in the summary.

**Comment by lynnfaraday** [comment]
@plusjade: I had summary_lines set to 999 and the example posts were very short, so I don't think it's a summary issue.  Unless there's some special summary logic I'm missing that would truncate the last line of the post?

**Comment by plusjade** [comment]
@lynnfaraday I cannot reproduce this. I've tried both on a sample blog with the exact info you've given me in the above comment as well as in a cucumber test outlined below. (just checked in a cucumber environment which will possibly make it easier to setup tightly controlled situations such as your scenario)

``` cucumber
Feature: Test
  ...
  Scenario: Test
      Given the file "widgets/foo/default.html" with body:
      """
      TEST1
      TEST2
      TEST3
      """
      And the file "essays/hello.md" with body:
      """
      Para1

      {{{ widgets.foo }}}

      Para2
      """
    When I compile my site
    Then my compiled site should have the file "essays/index/1/index.html"
    And this file should have the content node "div.summary:Para1 TEST1 TEST2 TEST3 Para2"

```

P.S. To run the test, git clone the latest master, bundle install, then:
1. place the above code in `features/test.feature`
2. Run `cucumber features/test.feature`

You can also comment out this line: https://github.com/ruhoh/ruhoh.rb/blob/master/features/support/helpers.rb#L68 so the sample site directory will stay in tack for inspection at `ruhoh/__temp/`

**Comment by lynnfaraday** [comment]
@plusjade - Yeah, I grabbed the latest code and now I can't repro it either.  Possibly I had messed something up in merging in the changes, or maybe it was fixed incidentally by something else (the former being more likely).   At any rate, it appears to be fixed now.  Thanks.
