### ISSUE TITLE
RSS feed not picking up post description

### ISSUE THREAD

**Issue by davedoesdev** [ruhoh/ruhoh.rb#182]
(Ruhoh 2.2)

resources/pages/compiler.rb has this:

``` ruby
xml.description_ (page.try(:description) ? page.description : view.render_content)
```

However, my feed always has the full content in, _not_ the page's description

If I do this just before the line above:

``` ruby
puts page.description
```

Then I see the description

However,

``` ruby
puts page.try(:description)
```

returns `nil`. Something wrong with `page.try` I think - is page a BasicObject?

**Comment by davedoesdev** [comment]
try (base/model.rb) should read:

```
def try(method)
  return __send__(method) if respond_to?(method)
  return data[method.to_s] if data.key?(method.to_s)
  false
```

At the moment, it's:

```
def try(method)
  return __send__(method) if respond_to?(method)
  return data[method] if data.key?(method.to_s)
  false
end
```

**Comment by plusjade** [comment]
Sorry guys, that implementation is an artifact of some major code refactoring..I'm not entirely sure we still need it but @davedoesdev fix looks good nonetheless!

**Comment by davedoesdev** [comment]
It's nice to be able to have the description in the rss feed instead of the content - really I want subscribers just to see a short precis. A lot of the formatting isn't going to carry across to feedly or innoreader (let alone some native app) anyway.

Btw I've ported the hooligan theme to RuhohSpec 2.1
