### ISSUE TITLE
Google-Prettify doesn't format Mustache

### ISSUE THREAD

**Issue by wzpan** [ruhoh/ruhoh.rb#187]
Hello,

As I try to use Google Prettify to format a piece of mustache code:

```
{{ toc }}
```

I found that it cannot be escaped but directly parsed by mustache. How to escape and render mustache code?

**Comment by wzpan** [comment]
Well, after reading the markdown source code of docs from ruhoh.com, I found that by embracing `{{#raw_code}}`...`{{/raw_code}}` outside of the mustache code works. Thanks again.

**Comment by plusjade** [comment]
Glad you found it!  =)  sorry that it is undocumented.
