### ISSUE TITLE
create subtree for themes

### ISSUE THREAD

**Issue by coolaj86** [ruhoh/ruhoh.rb#194]
Instead of including twitter and having to upgrade my theme when I only want to upgrade ruhoh core, put the theme somewhere else and let me submodule it as part of the install.

http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/17864475#17864475

```
pushd ~/blog
git subtree split -P twitter -b theme-only
popd

mkdir ~/twitter-v2
pushd ~/twitter-v2
git init
git pull ~/ruhoh.rb twitter-v2
popd

pushd ~/ruhoh.rb
git rm -rf twitter
git push
popd

git submodule add git@github.com:ruhoh/twitter.git twitter
```

And then modify the installation instructions to include

```
git clone ---blog---
cd ---blog---
git submodule init
git submodule update
```

**Comment by plusjade** [comment]
Tracking at: https://github.com/ruhoh/theme-twitter-bootstrap-2
