### ISSUE TITLE
permalink ignores ".html"

### ISSUE THREAD

**Issue by coolaj86** [ruhoh/ruhoh.rb#197]
In config.yml I have `permalink: "/articles/:title.html"` which produces `/articles/:title/index.html`.

Likewise in `posts/articles/vhosts-with-nodejs.md` I specify `permalink: "/articles/vhosts-with-nodejs.html"`, but it still produces `/articles/vhosts-with-nodejs/index.html`

This is a problem because I have to add redirect logic to my server for older posts.

**Comment by Stebalien** [comment]
IIRC, that is a documentation bug. Try setting `permalink_ext: true`.

**Comment by coolaj86** [comment]
confirmed works

however, I feel that this should be implicit. If I specify .html, use .html. If I don't specify .html, use /index.html

**Comment by wzpan** [comment]
Ditto! Good advice.

**Comment by mingcheng** [comment]
I got another problem,  when I use

permalink: "/:filename.html"
permalink_ext: true

the file output is 'xxx.md.html', I wanna its outputs 'xxx.html', so How?
