### ISSUE TITLE
weird install error

### ISSUE THREAD

**Issue by cboettig** [ruhoh/ruhoh.rb#2]
Somehow I messed up the gem install.  

```
 sudo gem install ruhoh
Invalid gemspec in [/var/lib/gems/1.8/specifications/ruhoh-0.0.3.gemspec]: invalid date format in specification: "2012-03-30 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/directory_watcher-1.4.1.gemspec]: invalid date format in specification: "2011-08-30 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/ruhoh-0.0.3.gemspec]: invalid date format in specification: "2012-03-30 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/directory_watcher-1.4.1.gemspec]: invalid date format in specification: "2011-08-30 00:00:00.000000000Z"
Successfully installed directory_watcher-1.4.1
Successfully installed ruhoh-0.0.3
2 gems installed
Installing ri documentation for directory_watcher-1.4.1...
Installing ri documentation for ruhoh-0.0.3...
Installing RDoc documentation for directory_watcher-1.4.1...
Installing RDoc documentation for ruhoh-0.0.3...
```

```
boettig@wiglaf:~/Documents/code$ ruhoh new ruhohblog
Invalid gemspec in [/var/lib/gems/1.8/specifications/ruhoh-0.0.3.gemspec]: invalid date format in specification: "2012-03-30 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/directory_watcher-1.4.1.gemspec]: invalid date format in specification: "2011-08-30 00:00:00.000000000Z"
/usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:926:in `report_activate_error': Could not find RubyGem ruhoh (>= 0) (Gem::LoadError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:244:in `activate_dep'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:236:in `activate'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:1307:in `gem'
    from /usr/local/bin/ruhoh:18
```

**Comment by plusjade** [comment]
ruhoh has not been tested with ruby 1.8.x and is not officially supporting it. 
I'm going to close this ticket but I will add in a task to eventually look into officially supporting 1.8 and depending on how hard it is, will implement it.

Thanks for this issue, and your patience Carl, and if possible try it using ruby 1.9.x

**Comment by cboettig** [comment]
install with ruby 1.9.1 worked like a charm.

On Thu, Apr 19, 2012 at 1:07 AM, Jade <
reply@reply.github.com

> wrote:
> 
> ruhoh has not been tested with ruby 1.8.x and is not officially supporting
> it.
> I'm going to close this ticket but I will add in a task to eventually look
> into officially supporting 1.8 and depending on how hard it is, will
> implement it.
> 
> Thanks for this issue, and your patience Carl, and if possible try it
> using ruby 1.9.x
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ruhoh/ruhoh.rb/issues/2#issuecomment-5216801

## 

Carl Boettiger
UC Davis
http://www.carlboettiger.info/
