### ISSUE TITLE
Promote randomly chosen posts

### ISSUE THREAD

**Issue by bjornmeansbear** [ruhoh/ruhoh.rb#207]
I'm working on using ruhoh to power a portfolio and am wondering if there is anyway to have it print out 5 random items from a collection? I searched both the documentation and the issue queue to see if an answer laid anywhere, but I can't seem to find it.

I was thinking something like:

```
<ul>
{{# pages.latest }}
  <li>
    <a href="{{url}}">{{title}}</a>
    {{{ content }}}
  </li>
{{/ pages.latest }}
</ul>
```

only using {{pages.random}}, and then setting a limit in the config just like can be done for latest... is this something that could be in a plugin?

Thanks.

**Comment by plusjade** [comment]
@bjornmeansbear here's a plugin that should do the trick:

``` ruby
# ./my-blog/plugins/pages_random.rb

module PagesRandom

  # Return n random page objects.
  # Limit can be set in config.yml:
  #   pages:
  #     random_limit: 10
  def random
    limit = config['random_limit'].to_i
    limit = limit > 0 ? limit : 5
    all.sample(limit)
  end

  # Return n random page objects.
  # Limit can be set dynamically by chaining the method call:
  #   {{# pages.random_with_limit.25 }}
  #     <li><a href="{{ url }}">{{ title }}</a></li>
  #   {{/ pages.random_with_limit.25 }}
  def random_with_limit
    @random_with_limit ||= RandomProxy.new(self)
  end

  # Allows arbitrary responses to methods that can be cast to Integers.
  # ex: random_with_limit.5 where "5" can be cast to an Integer
  class RandomProxy < SimpleDelegator
    def method_missing(name, *args, &block)
      __getobj__.all.sample(name.to_s.to_i)
    end

    def respond_to?(method)
      (method.to_s.to_i > 0) ? true : super
    end
  end
end

Ruhoh::Resources::Pages::CollectionView.send(:include, PagesRandom)
```

In your views:

``` html
<h5>Random with config limit</h5>
<ul>
{{# pages.random }}
  <li><a href="{{ url }}">{{ title }}</a></li>
{{/ pages.random }}
</ul>

<h5>Random with embedded limit</h5>
<ul>
{{# pages.random_with_limit.4 }}
  <li><a href="{{ url }}">{{ title }}</a></li>
{{/ pages.random_with_limit.4 }}
</ul>

```

### Usage

#### pages.random

Limit can be set in configuration:

``` yaml
pages:
  random_limit: 3 # defaults to 5 in the above example plugin
```

#### pages.random_with_limit

Limit can be set dynamically by chaining the method call:

``` html
limit: 1
{{# pages.random_with_limit.1 }}
  <li><a href="{{ url }}">{{ title }}</a></li>
{{/ pages.random_with_limit.1 }}

limit: 25
{{# pages.random_with_limit.25 }}
  <li><a href="{{ url }}">{{ title }}</a></li>
{{/ pages.random_with_limit.25 }}
```

**Comment by bjornmeansbear** [comment]
This is perfect. Thanks! I appreciate you looking this over so quickly. It would have taken me days to bash a much cruder version of this out myself.

**Comment by plusjade** [comment]
No problem, I'm really looking to get into user advocacy; outlining ways in which users are and can use ruhoh. 

I've spent so much time being in programmer-mode, thinking "look how cool this internal library is!". Now that the API is a bit more stable and I have some coding support from @Stebalien and @coolaj86 I think it's really valuable to do user-facing stuff like tutorials, plugin directory, fix up themes, encourage sharing, and fix user's problems like permalink-slugs and all the stuff I wouldn't otherwise be aware of if it weren't for users speaking up.

Eh, just a long way to say thank you for using the product and I hope to support users as a first priority in the coming iterations!

**Comment by bjornmeansbear** [comment]
Great. Well, I'll keep posting things that I get stumped by, and I'll clue you in if I solve anything in an interesting way. Thanks again.
