### ISSUE TITLE
what about other VCS like BZR or HG?

### ISSUE THREAD

**Issue by timmie** [ruhoh/ruhoh.rb#21]
Hello,
there are other depeloper communities at Launchpad and google code.

Your solution just looks to nice to be missing these repositores...

Would it be feasibile?

**Comment by plusjade** [comment]
@timmie I agree and I am serious when I say ruhoh's core vision is to enable _all developers_ to publish content. Toward that end it would be worth supporting other VCSs.  The one problem I have is I personally don't know much about the other systems so I would/could not prioritize developing solutions in lieu of other core issues (being this is still beta and all).

I think it is worth supporting other VCSs but I would need help to accomplish that. Any starting points or help would be much appreciated! Feel free to release you thoughts out in this thread.

**Comment by davejlong** [comment]
How about install instructions for post.ruhoh.com so that we can contribute to that to enable other VCS tools. I also wanted to look at adding a feature to support git submodules in repos so that themes and content can be separate. I guess I am really posting an issue with post.ruhoh.com's repo.

**Comment by plusjade** [comment]
@davejlong I just updated the README with some quick instructions: https://github.com/ruhoh/post.ruhoh.com#readme

Let me know if you need any more help getting it running on localhost. Supporting other services would definitely be fantastic, so good luck to you!

**Comment by plusjade** [comment]
Discussion is officially moved to a post.ruhoh.com [issue](https://github.com/ruhoh/post.ruhoh.com/issues/2)
