### ISSUE TITLE
sorting descending by timestamp in title?

### ISSUE THREAD

**Issue by bryanrasmussen** [ruhoh/ruhoh.rb#214]
Hi, 

It seems that files in the posts folder are sorted ascending by title, whereas it is common in blogs to have the latest post first, which if you have the timestamp in the title does not work. 
How do you sort descending so that the latest post shows up first?

**Comment by plusjade** [comment]
@bryanrasmussen the "posts" folder should be sorting by "date" attribute which you can see is set here:
https://github.com/ruhoh/blog/blob/master/config.yml#L34-35 Note from this configuration that you can technically set sort mode on any attribute in "asc" or "desc" order.

Note that default sort mode, as you've discovered is in fact "title". So whenever you make new folders or "collections" as they are called, if you want to sort on date you need to configure the collection:

``` yaml
# in config.yml

"my-custom-folder":
  "sort": ["date", "desc"]
```

Note that sorting by date requires the "date" attribute to be set for every file in that collection or an error will be raised. The date is not recognized from the title attribute, rather from the date attribute like this:

``` html
# in my-custom-folder/some-file.md
---
title: "hello world"
date: "2012-12-12"
description: "Oh yeah"
---

... page body goes here ...
```

Dates should be strings in the form YYY-MM-DD
Currently there is no granularity beyond "day" which is a known problem that will be addressed. i.e. if you have posts having the same day the order is not guaranteed.

Please link to your blog source if it is available online and I can help you troubleshoot further.

Hope this helps.

**Comment by plusjade** [comment]
I just hit publish but i realize the title of this issue is literally "timestamp in title". Technically ruhoh should still support the date in the title format (an artifact of jekyll-roots) but you may have highlighted a bug in that the sorter is not able to find the date as an attribute. I have to look deeper into this and make a test case for this, but see if setting explicit configuration solves the problem.
