### ISSUE TITLE
Documentation bug - install bootstrap theme required

### ISSUE THREAD

**Issue by nevware** [ruhoh/ruhoh.rb#219]
The documentation (http://ruhoh.com/docs/2/installation/#toc_2) is inaccurate - 
    bundle exec rackup -p 9292
fails with an error changing directory unless the Twitter bootstrap theme is present.

**Comment by plusjade** [comment]
Good catch. Technically this is not part of the "introduction" docs but I did find the problem. In the init-ruby files the `config.yml` is specifying the theme folder which its should not be doing: https://github.com/ruhoh/init-ruby/commit/fd8c10fcdf7da8cfeb1a5c0f67fdb0efa22fc1fb

Fixed!
