### ISSUE TITLE
Post-Receive Service Hook Failure: wrong number of arguments(2 for 1)

### ISSUE THREAD

**Issue by niedzielski** [ruhoh/ruhoh.rb#22]
1. Create a new repository.
2. Add a post-receive service hook, http://post.ruhoh.com.
3. Run the advertised steps:

``` bash
git clone git://github.com/ruhoh/blog.git niedzielski.ruhoh.com
cd niedzielski.ruhoh.com
git remote set-url origin git@github.com:niedzielski/niedzielski.ruhoh.com.git
git push origin master
```
1. Visit niedzielski.ruhoh.com and get a 404. Logs say: wrong number of arguments(2 for 1)

**Comment by ranxiang** [comment]
same issue on ranxiang.ruhoh.com

**Comment by plusjade** [comment]
Darn, I'm getting that too. I'm just about to sleep but I'll address this tomorrow. The localhost stuff should all work though! Thanks for your patience.

**Comment by plusjade** [comment]
This error should be fixed now. Please redeploy and ensure this work. All I did was do a hard restart on my web-server but apparently it's working now. Please verify, thank you.

**Comment by plusjade** [comment]
I'll ping @niedzielski and @ranxiang in case you guys didn't get updated.

**Comment by niedzielski** [comment]
Fixed. Works perfectly. Thank you!

**Comment by LiquidMark** [comment]
I'm getting a 404 on LiquidMark.ruhoh.com

I followed instructions:

<pre>
  git clone git://github.com/ruhoh/blog.git LiquidMark.ruhoh.com
  cd LiquidMark.ruhoh.com
  git remote set-url origin git@github.com:LiquidMark/LiquidMark.ruhoh.com.git
  git push origin master
</pre>


No clue why it doesn't work -- all I get is the 404 not found

**Comment by plusjade** [comment]
@LiquidMark have you enabled a webhook on GitHub's end? The web-hook must post to:

```
http://post.ruhoh.com
```

**HOW TO:** Go to your [LiquidMark.ruhoh.com](https://github.com/LiquidMark/LiquidMark.ruhoh.com) repository page on GitHub, then follow these instructions: http://help.github.com/post-receive-hooks/

After you do this, you can click on the TEST HOOK button to send the hook to post.ruhoh.com service.  The hook will trigger whenever you push commits up to GitHub (thereby updating your website). Please let me know once you do this and I'll ensure everything is working on my end after that.
