### ISSUE TITLE
Empty title for Pages throws an error

### ISSUE THREAD

**Issue by wwchen** [ruhoh/ruhoh.rb#220]
# > ruhoh

...
 pages draft <title>
   Create a new draft. Title is optional.
..
# > ruhoh pages draft

~/.rvm/gems/ruby-1.9.3-p327/gems/ruhoh-2.4/lib/ruhoh/resources/pages/client.rb:68:in `gsub': can't convert nil into String (TypeError)

diff on line 70 in client.rb:
- .gsub('{{TITLE}}', @args[2])
- .gsub('{{TITLE}}', (@args[2] || ''))

**Comment by wzpan** [comment]
Confirm this bug. I came across it too.

**Comment by wwchen** [comment]
Pull available https://github.com/ruhoh/ruhoh.rb/pull/221
