### ISSUE TITLE
QuickStart fails 

### ISSUE THREAD

**Issue by lgs** [ruhoh/ruhoh.rb#222]
I was giving ruhoh a try but [QuickStart](http://ruhoh.com/docs/2/quickstart/) fails giving me back a runtime error: 

<pre>
No generated page URL matches '/' using file pointer: 'nil'. Since the file pointer was nil we tried to load a pagination view but it didn't work;
 Expected the format to be: '<valid_resource_name>/page_number'
</pre> 

see the full stacktrace:

<pre>
lsoave@base:/home/test/ruhoh-site$ bundle exec rackup -p 9292
=> Start watching: /home/test/ruhoh-site
[2013-09-21 10:48:20] INFO  WEBrick 1.3.1
[2013-09-21 10:48:20] INFO  ruby 2.0.0 (2013-06-27) [x86_64-linux]
[2013-09-21 10:48:20] INFO  WEBrick::HTTPServer#start: pid=4218 port=9292
- previewing page:
   nil
RuntimeError: No generated page URL matches '/' using file pointer: 'nil'. Since the file pointer was nil we tried to load a pagination view but it didn't work;
 Expected the format to be: '<valid_resource_name>/page_number'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/ruhoh-2.4/lib/ruhoh/resources/pages/previewer.rb:35:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    /home/lsoave/.rvm/gems/ruby-2.0.0-p247@rails-4.0.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
    /home/lsoave/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
    /home/lsoave/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /home/lsoave/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
127.0.0.1 - - [21/Sep/2013 10:48:25] "GET / HTTP/1.1" 500 58317 0.0660
127.0.0.1 - - [21/Sep/2013 10:48:25] "GET /favicon.ico HTTP/1.1" 200 - 0.0040
127.0.0.1 - - [21/Sep/2013 10:48:26] "GET /favicon.ico HTTP/1.1" 200 - 0.0027
</pre>

<pre>
lsoave@base:/home/test/ruhoh-site$ rvm list

rvm rubies

=* ruby-2.0.0-p247 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
</pre>

**Comment by plusjade** [comment]
Sorry, I need to improve the tutorial, this step is actually expected as if you are following the steps you will not have any content at this stage. The next part of the tutorial (http://ruhoh.com/docs/2/quickstart/#toc_2) shows you how to make the root page:

Make the file at `ruhoh-site/_root/index.md` with the content:

``` markdown
# Hello World
> A profound quote.
### Fruits I like
- apples
- oranges
- watermelons
- tomatoes
- avocados

```

Then reload the page at [http://localhost:9292](http://localhost:9292)

Does this work?

**Comment by lgs** [comment]
It works fine, thank you.  

<pre>
lsoave@base:/home/test/ruhoh-site$ bundle exec rackup -p 9292
=> Start watching: /home/test/ruhoh-site
[2013-09-21 11:11:41] INFO  WEBrick 1.3.1
[2013-09-21 11:11:41] INFO  ruby 2.0.0 (2013-06-27) [x86_64-linux]
[2013-09-21 11:11:41] INFO  WEBrick::HTTPServer#start: pid=4463 port=9292
- previewing page:
   {"id"=>"index.md", "realpath"=>"/home/test/ruhoh-site/_root/index.md", "resource"=>"_root"}
127.0.0.1 - - [21/Sep/2013 11:11:55] "GET / HTTP/1.1" 200 - 0.0173
</pre>

I also have to say that's a very nice project too.

**Comment by plusjade** [comment]
Thanks for the encouraging words! Let me know if any other parts don't make any sense as I'm sure there are!
