### ISSUE TITLE
Docs should mention how 2.4+ makes layouts nestable

### ISSUE THREAD

**Issue by binaryphile** [ruhoh/ruhoh.rb#226]
Per https://github.com/Stebalien/ruhoh.rb/commit/0742b12cb10798e869ebb97e9ae97e55c0f31ebe, nested layouts now can use {{{ content }}} for subcontent at all levels.  The 2.5 docs still say you can only have one level of nesting and use {{{ page.content }}}.  Suggesting the docs be updated.

**Comment by plusjade** [comment]
@binaryphile thanks, I've updated the docs! http://ruhoh.com/docs/2/layouts/ (namely the Nesting section)
