### ISSUE TITLE
1.9.3 Deprecation of iconv

### ISSUE THREAD

**Issue by davejlong** [ruhoh/ruhoh.rb#23]
In Ruby 1.9.3 [-p125] the iconv library has been deprecated and using String#encode is recommended instead. I see a message about it on every ruhoh command. The full message is as follows:

```
/Users/davejlong/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
```

**Comment by plusjade** [comment]
Not seeing this anymore in 2.1
