### ISSUE TITLE
will the ruhoh support customer specify markdown: parser?

### ISSUE THREAD

**Issue by marvin-min** [ruhoh/ruhoh.rb#235]
Dear:
    ruhoh is a very good tool for writting.but,i can't find anywhere to custom markdown parser , jekyll can support this ! and you have any plan to support it ?  thanks very much ~!

**Comment by plusjade** [comment]
Yes the markdown library is called a "converter" in ruhoh. You can re-implement  the converter any way you want via the plugin system: http://ruhoh.com/docs/2/plugins/#toc_7 

Let me know if you need help with any special markdown library configuration.
