### ISSUE TITLE
Image Style Snippet

### ISSUE THREAD

**Issue by lynnfaraday** [ruhoh/ruhoh.rb#236]
Right now if I want to display an image in a blog post, I just use the default markdown syntax:

> ![caption](url)

Since I do this a lot, I would really like to pretty up the styling a bit.  Incredibly trivial example:

> <table class="pretty-image"><tr><td> ((image goes here)) </td></tr> 
> <tr><td> ((caption goes here)) </td></tr></table>

Is there a good way to encapsulate this snippet as a template in ruhoh so I don't have to paste in that HTML everywhere there's an image?

A partial could work if the image info was in the post metadata, but that just doesn't feel right.  And it limits you to only one image per post, which is arbitrarily limiting.

**Comment by Stebalien** [comment]
Personally, I would use the following custom converter. It will caption ALL markdown images:

``` ruby
require 'redcarpet'
require 'nokogiri'

class HTMLCustom < Redcarpet::Render::HTML
  def image(url, title, alt)
    return if url.nil? or url.empty?
    builder = Nokogiri::XML::Builder.new do |doc|
      doc.figure {
        doc.img({:src => url}.tap { |h|
          h[:title] = title unless title.nil? or title.empty?
          h[:alt] = alt unless alt.nil? or alt.empty?
        })
        doc.figcaption(alt) unless alt.nil? or alt.empty?
      }
    end
    builder.to_xml
  end
end

class Ruhoh
  module Converter
    module Markdown
      def self.convert(content)
        markdown = Redcarpet::Markdown.new(HTMLCustom.new(:with_toc_data => true),
          :autolink => true, 
          :fenced_code_blocks => true, 
        )
        markdown.render(content)
      end
    end
  end
end
```

You can also do this with partials:

```
----
title: "My Title"
imageA:
  caption: "My caption"
  url: "http://example.com/img.png"
----
{{# imageA}}
{{> captioned_image }}
{{/ imageA }}
```

`captioned_image.html`:

``` html
<figure>
<img src="{{url}}" alt="{{caption}}" />
<figcaption>{{caption}}</figcaption>
</figure>
```

**Comment by lynnfaraday** [comment]
@Stebalien  - Worked great, thanks.
