### ISSUE TITLE
Next/Previous Loop

### ISSUE THREAD

**Issue by bjornmeansbear** [ruhoh/ruhoh.rb#242]
I tried searching for this but didn't see that anyone had asked about this before. Is it possible to make page.next output a link to the oldest post when you are on the newest post (and page.previous go from the oldest post to the newest post)? I'm working on a portfolio site and would like to make a continuos loop since there isn't an interest in chronology, just an easy flow from project to project no matter where you start. I haven't been able to figure this out on my own from documentation or trial and error.

**Comment by Stebalien** [comment]
The easiest way is to use the following navigation template:

``` HTML
<ul>
  {{# page.previous }}
    <li class="prev"><a href="{{ url }}" title="{{ title }}">&larr; Previous</a></li>
  {{/ page.previous }}
  {{^ page.previous }}
  {{# page.collection.all.first}}
    <li class="prev"><a href="{{ url }}" title="{{ title }}">&larr; Previous</a></li>
  {{/ page.collection.all.first}}
  {{/ page.previous }}

    <li><a href="{{urls.base_path}}archive">Archive</a></li>

  {{# page.next }}
    <li class="next"><a href="{{ url }}" title="{{ title }}">Next &rarr;</a></li>
  {{/ page.next }}
  {{^ page.next }}
  {{# page.collection.all.last}}
    <li class="next"><a href="{{ url }}" title="{{ title }}">Next &rarr;</a></li>
  {{/ page.collection.all.last}}
  {{/ page.next }}
</ul>
```

You could also write a plugin to modify `Ruhoh::Base::PageViewable`'s `next` and `previous` methods.

**Comment by bjornmeansbear** [comment]
Great, this is a perfect solution, didn't think of this.
Works like a charm.
thanks.
