### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by LiquidMark** [ruhoh/ruhoh.rb#25]
I'm getting a 404 on LiquidMark.ruhoh.com

I followed instructions:

<pre>
  git clone git://github.com/ruhoh/blog.git LiquidMark.ruhoh.com
  cd LiquidMark.ruhoh.com
  git remote set-url origin git@github.com:LiquidMark/LiquidMark.ruhoh.com.git
  git push origin master
</pre>

No clue why it doesn't work -- all I get is the 404 not found

**Comment by plusjade** [comment]
@LiquidMark have you enabled a webhook on GitHub's end? The web-hook must post to:

```
http://post.ruhoh.com
```

**HOW TO:** Go to your [LiquidMark.ruhoh.com](https://github.com/LiquidMark/LiquidMark.ruhoh.com) repository page on GitHub, then follow these instructions: http://help.github.com/post-receive-hooks/

After you do this, you can click on the TEST HOOK button to send the hook to post.ruhoh.com service.  The hook will trigger whenever you push commits up to GitHub (thereby updating your website). Please let me know once you do this and I'll ensure everything is working on my end after that.

**Comment by plusjade** [comment]
@LiquidMark, I see you got the POSTing working. There was also another issue with capitalized letters in GitHub user names. I've pushed a fix and this problem should be fine now. You can use the service as described, thanks!
Logs are looking healthy: http://liquidmark.ruhoh.com/log.txt

**Comment by LiquidMark** [comment]
Jade,

Thank you for your help!

-Mark Molloy

On Thu, May 17, 2012 at 1:25 AM, Jade <
reply@reply.github.com

> wrote:
> 
> @LiquidMark, I see you got the POS working. There was also another issue
> with capitalized letters in GitHub user names. I've pushed a fix and this
> problem should be fine now. You can use the service as described, thanks!
> Logs are looking healthy: http://liquidmark.ruhoh.com/log.txt
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ruhoh/ruhoh.rb/issues/25#issuecomment-5759048

## 
- Mark Molloy
  (641)218-8265

**Comment by plusjade** [comment]
No problem. Please continue to offer usage feedback, thanks!
