### ISSUE TITLE
data.yml cascade for themes is not friendly

### ISSUE THREAD

**Issue by zxaos** [ruhoh/ruhoh.rb#253]
(The short version: having data.yml in the theme directory be higher precedence than the site directory version makes theme installation and configuration more complicated than it should be)

The theme system in ruhoh seems like it's designed to allow themes to be dropped in and activated/deactivated easily, an without _requiring_ any modifications to the new theme.

This breaks down in the handling of the data.yml file, though. Because of the order of the cascade, the theme-provided data.yml file overrides the data.yml in the main ruhoh directory.

If a theme provides a data.yml file, it's no longer a simple installation since you must either (1) go into the theme and modify the data.yml file or (2) copy the data.yml file out of the theme into your main site director. Both of these approaches present problems.

The first option means that theme installation is no longer just a simple git clone and set theme. It also means that data attributes which would reasonably not change across different themes, such as site name and author information, must be re-set whenever a new theme is installed, and may provide a more complicated theme upgrade path for non-technical users (since the git clone would then have local changes).

The second option means the user is either overwriting existing configuration in data.yml or having to hand-merge the attributes the theme requires with whatever might be in their site data.yml.

I'd like to propose a couple of solutions which I think might make this situation work a bit better. One would be to have the cascade order for the data.yml file _only_ in the theme be lower than the main site. This could be confusing, however. The other way would be to have ruhoh expect not a data.yml file in a theme, but a data_defaults.yml which would supply attributes to the data collection only if the corresponding attribute was not set in the main site data.yml (to ensure that themes still have reasonable defaults when first installed). The downside to this method is that there could conceivably be a situation where a same named attribute was used in a two different themes for wildly different purposes and might cause unexpected behaviour when switching between themes if set in the main data.yml file.

**Comment by plusjade** [comment]
Would you support a simple deep-merge down the cascade? This is the current (in the master branch) way config.yml is handled. `system/config.yml -> blog/config.yml -> theme/config.yml` is just a merged hash, the latter attributes naturally overwriting any former attributes set of the same name.

I'm thinking is this the easiest and most _inline_ solution with how everything currently works. As for possible conflicts I'm thinking there would be a gentleman's agreement that stuff like `author` shouldn't be overwritten by third party themes/plugins/etc.

Thoughts?

**Comment by zxaos** [comment]
It looks like in 5a8fd48 the values in theme/config.yml are still replacing those from blog/config.yml which was the issue? (Sorry I'm new to the codebase and I'm not fully understanding what 5a8fd48 changes from the 2.5 gem )

**Comment by plusjade** [comment]
Yes they theme data replaces data attributes of the same key.  This change
makes it so the data is merged rather than the entire file replaced.

The issue then is the theme should probably not be the highest priority is
the cascade so as to allow it act as  over writable defaults.

I understand your issue more now.   This likely is better addressed in 3.0.
Unless we go for the additional config_defaults approach.

**Comment by zxaos** [comment]
> This likely is better addressed in 3.0. Unless we go for the additional config_defaults approach.

Fair enough. The deep merge is still an appreciated improvement to the current cascade ordering.

I'm torn about whether I think config_defaults or modifying the cascade is better. I think the changing the cascade is cleaner but less intuitive maybe. Either change would probably cause some issues with existing themes, so it makes sense to wait for a major version bump.

Thanks for looking into this!
