### ISSUE TITLE
access list elements in Mustache section

### ISSUE THREAD

**Issue by waynedpj** [ruhoh/ruhoh.rb#258]
ahoy,

  [here](http://ruhoh.com/docs/2/pages/#toc_24) in the docs for ruhoh there is the following example top metadata:

```

---
title: Oh Happy Day
icon : sun
days :
  - monday
  - tuesday
--- 
```

unfortunately the example does not show how to access the elements of the `days` list inside a Mustache template.  an imaginary solution would be something like:

```
the days of the week are:
{{#days}}
  {{@element}}
{{/days}}
```

i have been researching Mustache and trying different things but so far i have been unable to find a way to do this, or even find out if it is possible.  perhaps these list elements need to have a name/key defined?

  thanks in advance for any help.

peace, w

**Comment by plusjade** [comment]
Array elements are accessible via `.`

```
{{# page.days }}
  {{ . }}
{{/page.days}}
```

**Comment by waynedpj** [comment]
thank you, that simplifies things greatly!
