### ISSUE TITLE
how to include a block helper plugin?

### ISSUE THREAD

**Issue by waynedpj** [ruhoh/ruhoh.rb#259]
ahoy all,

  i am trying to write my first block helper (and my first Ruby code) and though i have seen some examples of block helpers in the main ruhoh source #68 i cannot figure out how to get a simple block helper included when it is in a plugin.  currently i have:

```
module BlockHelpers
  def ahoy(subcontext)
    puts "ahoy called with subcontext = '#{subcontext}'"
    "ahoy!"
  end

  def ahoy_ahoy
    "ahoy ahoy!"
  end
end
Ruhoh::Views::Helpers.send(:include, BlockHelpers)
```

and trying to use it in the following template:

```
{{#ahoy}}
some text
{{/ahoy}

then
{{ahoy_ahoy}}
```

any help would be appreciated and i will use it to update the [block helper docs](http://ruhoh.com/docs/2/plugins/#toc_5).

thanks in advance.

**Comment by waynedpj** [comment]
so far using this line seems to work for adding a block helper:

```
Ruhoh::Views::MasterView.send(:include, BlockHelpers)
```

not sure if this is the "correct" way?

**Comment by Stebalien** [comment]
This is how I do it. Also, it's "documented" (should probably also be documented elsewhere) here: http://ruhoh.com/docs/2/upgrading/#toc_17

**Comment by waynedpj** [comment]
@Stebalien thanks for confirming that.

i tried to create a pull request to update the ruhoh.com docs

https://github.com/waynedpj/ruhoh.com/commit/06072532db2c2301e67436bddafb099662d64c34

however, i am not sure if it worked.. still trying to get my head around git!

peace, w
