### ISSUE TITLE
Omit all meta-data requirements for posts and pages

### ISSUE THREAD

**Issue by plusjade** [ruhoh/ruhoh.rb#27]
#### Why

Allows for truly write-first workflow. Idea came to me when a user was pushing posts to ruhoh.com without running ruhoh gem locally. In this case he has no idea how a post should be formatted since he has no access to the ruhoh command-line client.  The client is not necessary if you push to a service.
#### How

The only **required** meta-data for posts is the date and layout, the title will be inferred from the filename.

The layout can be defaulted to 'post' and/or set globally (this is a good separate feature anyway).
The date can be omitted entirely and posts will just not have dates. Only issue would be the archive. We can add an "undated" collection, that will always be appended to the list when sorting chronologically.

Thoughts, objections?

EDIT: or dates can be inferred from file creation time at compile step? I don't know how reliable that data will be though...

**Comment by lynnfaraday** [comment]
+1 for the idea.  FYI - I've had rough experiences with file create date, especially if you move things from one computer to another, or across OS's, etc.

**Comment by lynnfaraday** [comment]
@plusjade : Two ideas kind of in the same vein:
- Is it possible that the ruhoh command tool can let you assign the title when you create the draft? 
- Is it really so bad to have the date in the title as well?  I believe Jekyll did this.  I assume there was some reason for changing it but I found it convenient to be able to browse posts by date on my local drive.

**Comment by plusjade** [comment]
@lynnfaraday 
- Yes I am re-adding in optional title passing in the next release.
- Dates in the filename are now _optional_. So you can still specify them manually and they will work like before, but there is no longer an automated way to do this. The reason I took it out is to remove friction from publishing. The software should not require such stringent inputs from the _user_ -- publishing should be fun!

**Comment by plusjade** [comment]
https://github.com/ruhoh/ruhoh.rb/commit/028587832aef23883d848b0b902cc4846af7ea63 provides automatic global layout defaults to posts and pages. Dates are still required for the time being.
