### ISSUE TITLE
Add support for n recent posts with summary

### ISSUE THREAD

**Issue by thefotios** [ruhoh/ruhoh.rb#28]
Maybe somebody has a working version of this, but I couldn't get it working just yet. I think my problem may simply be accessing the content of a post from another page. Is this even possible?

But the idea would be to have a partial for showing a number of recent posts and short summaries. This could be used as an index page or for a specific category. It would also include a link to the full path, the date published, and whether there are comments.

I've added a sample partial and  a screenshot.

https://gist.github.com/2727495

**Comment by plusjade** [comment]
@fotioslindiakos this functionality will be natively supported in a future release. Until then you can use this plugin: 

https://gist.github.com/2705778

However there is still the problem of the `content` attribute. ruhoh does not actually store the content body of every page/post, it only stores the content for the _current_ page. Since the id is essentially a pointer to the filename, whenever we need the actual content of a page we just parse the file -- this keeps the data-structures lean.

I can refactor the mustache helpers to lazy-load the content in a future release, but until then let me know what you think of the current `post_limit_5` style, since if there are no better ideas, it will get added in that format.

**Comment by thefotios** [comment]
Ya, I am using that plugin, and it's working fine. 

My main problem is getting the content, maybe there could be a `post_with_content` helper that gets the content too. So we could do something like

```
{{# post_limit_5 }}
  {{# post_with_content }}
    {{> post_summary }}
  {{/ post_with_content }}
{{/ post_limit_5 }}
```

**Comment by plusjade** [comment]
I'm pretty sure I can get it to where mustache will just lazy load the content. In other words `content` won't be attached to the page objects as a literal key/value but rather it will be a function call that will fetch the content from the file. This requires that all page objects are presented within their own mustache views though -- these problems all being internal, so you don't have to worry about it!

That way can do the more intuitive thing:

```
{{# post_limit_5 }}
  {{content}}
{{/ post_limit_5 }}
```

And also even a `{{summary}}` method which based on the most popular use-case, would provide a truncated-to-n-words-summary (as configurable in _config.yml). 

All of this, I'm sure, is possible, the bigger question I need to worry about is if this functionality will scale out across all/most of the different langage mustache implementations.

**Comment by thefotios** [comment]
Where are these templates defined? Maybe I can take a crack at implementing them.

**Comment by plusjade** [comment]
@fotioslindiakos I'm not sure what you are asking. What are you referring to when you say "templates" ? - Thanks.

**Comment by thefotios** [comment]
Guess I didn't use the correct term. I'm trying to see where `content` is defined, whether it's a variable somewhere or a function or what. That way I can see how this thing works and try to help out.

**Comment by lynnfaraday** [comment]
Currently there is no way to get at {{content}} for a post - that's part of what needs to be developed (per the 'lazy load/view' stuff plusjade was talking about earlier).

**Comment by plusjade** [comment]
Page content [accessor](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/page.rb#L77-80) and [mustache helper](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/templaters/rmustache.rb#L36-40) added in [ruhoh v.1.0.0.alpha](http://ruhoh.com/blog/releases/version-1-0-0-alpha/).

Your specific use case is documented here: [posts_latest index](https://github.com/ruhoh/blog/blob/master/pages/index.html#L16-26) Let me know how this works for you guys!

See [Configure documentation](http://ruhoh.com/usage/configure/) for configuring posts_latest and summary helpers.

**Note:** Feel free to open new feature-specific issues related to the new posts_latest, summary, and index features. e.g. iterate over specific category, tag, year, or pagination etc.

**Comment by thefotios** [comment]
I forgot to say thank you for this feature! Your example is exactly what I was looking for.

**Comment by plusjade** [comment]
@fotioslindiakos no problem, please keep the feedback coming. Thanks!
