### ISSUE TITLE
Permalinks with dashes do not work

### ISSUE THREAD

**Issue by davidmles** [ruhoh/ruhoh.rb#283]
I have configured this for my posts URLs:

```
posts:
  permalink: '/blog/:year-:month-:day-:title'
```

And after restarting the server, it fails to generate the URLs. It seems to have a problem understanding dashes, as it generates "http://example.com/blog" for each post.

**Comment by jasonmtroos** [comment]
This format used to work (most recently in v 2.1?) and now it's not. I've had to change my permalinks in order for links to work, which sort of goes against the "perma" part...?

Edit: see my pull request below for a quick and dirty solution. I have my permalinks back!
