### ISSUE TITLE
theme standards

### ISSUE THREAD

**Issue by afknapping** [ruhoh/ruhoh.rb#29]
maybe standardize the file-/folderstructure of themes, too, including a folder for `abstractions`, `src` or anything similar for [haml/sass/coffeescript/etc](https://github.com/ruhoh/ruhoh.rb/wiki/using-haml,-sass-and-coffeescript)?

while `layouts` is a descriptive name for the content, `css` and `js` describe the syntax used. i would prefer consistency, having `stylesheets`, `scripts`, `layouts` and `media` instead of eg `css`, `html`, `js` and `png`.

**Comment by afknapping** [comment]
ps: after two years of using the abandoned toto, you really hit a nerve with this. ruhoh basically adresses all the issues that came up during the time. awesome!

**Comment by plusjade** [comment]
You know, I never really processed that as a _difference_ (syntax vs role). This is an excellent point and will indeed add this into the next release. FWIW in 0.4.0 I'm breaking `_templates` directory structure entirely.

The new structure will look like this (with your edits)

```
- _pages
- _posts
- _partials
- theme-twitter
  - assets
    - media
    - scripts
    - stylesheets
  - layouts
    - default.html
    - page.html
    - post.html
  - partials  
```

Basically I didn't like the deep nesting that exists in the current `_templates` folder. So now we have most things in the root, including the theme folder which just namespaces layouts, assets and partials (theme partials overload system partials)

Any problems or suggestions? This is in 0.4.0 so let me know how it can be better!

**Comment by plusjade** [comment]
@filtercake re: your P.S. Thanks! I put more thought into this than you would ever think possible for a static blogging engine =)

As you can see the community is quite small right now, haven't done any marketing -- I'm more concerned with stabilizing the API before rolling out features and cool integrations like s3, dropbox and of course support for other languages. The point being, your feedback at this time is very likely guaranteed to shape the project so please do air your concerns.

**Comment by afknapping** [comment]
> I'm more concerned with stabilizing the API before rolling out features and cool integrations

i would say that is exactly the way to go :)

i agree that the `_templates`-folder is a bit messy right now, but having a `_themes`-folder does make sense (as does a `_plugins`-folder, etc.). having several themes in the root directory and needing to add "-theme" to each folder feels somewhat dirty.

besides that the new structure within the theme looks great to me.

i do miss the `_drafts`-folder. i use writeroom (iphone), which has its own closed folder on dropbox (which i like, because the app does not need access to my whole dropbox that way). on my machine i would want to `ln writeroom/drafts/` as `my_ruhoh_blog/_drafts/`.

not sure how something like the google prettify thing integrates. could that be a "module" which has its own `_modules` directory?

being a designer, i don't like the idea of these css-modules in general, because it gives an easy opportunity to visually mess things up. on the other hand i see how important customizable syntax highlighting is for the intended audience. i wouldn't want to have an opinion bout that from the hip but will  think about it.

as long as it's  defined what means what, it would imo be totally okay to have eg 
- plugins (ruby, used while compiling)
- widgets (functional html/js snippets)
- themes (layouts and assets)
- syntax-modules (css)

i'm new to moustache, but it feels weird to me that the partials do not have file suffixes.

i have not fully understood yet how pages, partials and layouts work together – but i guess that's coming from staring at ruhoh for six hours straight now :) i will sleep over it…

**Comment by plusjade** [comment]
Theme API has been stablized in ruhoh 2.1 http://ruhoh.com/docs/2/themes/

I think there can still be improvements but overall the structure is much simpler and we no longer make any assumptions on how to organize presentation assets, aside from core directory roles.

Feel free to log any specific improvements as new issues. Thanks for all the feedback!
