### ISSUE TITLE
Make a blog unavailable

### ISSUE THREAD

**Issue by moiatgit** [ruhoh/ruhoh.rb#292]
I'm trying to make an old blog unavailable. 
I've removed its contents from github but it can still be browsed. What else should I do in order to get rid of it?

**Comment by plusjade** [comment]
i can remove it manually. Can you paste your your URL to be sure.

**Comment by moiatgit** [comment]
http://moiatgit.ruhoh.com/
Thanks a lot!

**Comment by moiatgit** [comment]
It is there any problem with the deletion? May I do something on my side to help removing it?

**Comment by moiatgit** [comment]
After so many years, today it seems my old blog is finally unavailable. Hopping this is permanent, I'm closing this issue. Thanks @plusjade
