### ISSUE TITLE
Adding a robots.txt file?

### ISSUE THREAD

**Issue by MarcusRiemer** [ruhoh/ruhoh.rb#295]
When I add a robots.txt file to the `_root` folder ruhoh applies the template as if it were a "normal" page. Is there any easy way around this?

**Comment by ameuret** [comment]
- Add a YAML section at the top of your `robots.txt` file to specify a layout and a permalink:

```
---
title: The robots.txt file
permalink: '/robots.txt'
layout: bare-to-the-bone
---

User-agent: *
Disallow: /cgi-bin/
Disallow: /privatedir/
Disallow: /tutorials/blank.htm
```
- Create the `bare-to-the-bone.md` layout file in one of the layout locations:
  
  {{{content}}}

That's it.

**Comment by MarcusRiemer** [comment]
Ah, the combination of a permalink with a bare layout was too obvious for me, this would even work just fine for sitemaps. Thanks alot!

**Comment by ameuret** [comment]
Amazing T-Shirt. I did a semester in the PTL. It's a small world ! :smile:
