### ISSUE TITLE
How to access HTML parameters (for pagination)?

### ISSUE THREAD

**Issue by lynnfaraday** [ruhoh/ruhoh.rb#33]
Sorry if this is a noob-ish question.  When you're in one of the Helpers, how do you get at the HTML parameters for a ruhoh page, like query parameters and cookies?  They don't seem to be in self.context or in a 'params' variable like a standard rails controller -- unless I'm missing something.

Edit: Changing title to aid in future searches.

**Comment by plusjade** [comment]
@lynnfaraday there are no session cookies or parameters. Ruhoh is meant to compile to a static website when in production. May I ask what you are trying to accomplish so that I can give some input on whether or not it's possible and how to do it.

**Comment by lynnfaraday** [comment]
I was fiddling around with the recent posts view described in issue #28.  I got it to where index.html can show the most recent N posts, but now I'm trying to extend it to have (prev N) (next N) buttons and was exploring ways to go about doing that.   

I forgot for a moment that it all gets compiled... testing everything with rackup makes it feel more dynamic than it really is, I guess.  :)

I don't think there's going to be any clean way to do ..next N / prev N.

**Comment by plusjade** [comment]
@lynnfaraday pagination is a good idea. Jekyll does add custom functionality to specifically support pagination https://github.com/mojombo/jekyll/wiki/Pagination

Off the top of my head you'd probably want to create a custom mustache method specifically for pagination. Each page batch can be set in the config file, so you won't have to pass it via the method as you do with `posts_limit_5`. As jekyll does you might have to construct your own paginate object that utilizes `self.context['db']['posts']['chronological']` (an ordered array of posts) and has pointers to "previous" and "next".

One big issue is that the pages will have to be automatically generated at compile time. In other words if we have 100 posts at 10 posts per page, the compiler has to generate 10 physical files at the url /posts/page/1.html or whatever. 

Hopefully you can play with it a little and have a look at Jekyll's internals to see how they do it. 

I plan to support this feature natively so if we have to hack the gem, that's fine. I cannot personally get to this feature until I release the main overhauls I'm working on currently. I currently work in the [0.4.0 branch](https://github.com/ruhoh/ruhoh.rb/tree/0.4.0).

I'll keep this thread updated with current implementation ideas for supporting pagination. Thanks for bringing this up.

**Comment by lynnfaraday** [comment]
@plusjade : I have the building blocks for pagination working - a Paginator class (borrowed heavily from jekyll's version), a post_summary partial (since the summary view is a little different than the main page view), a recent_posts mustcache helper, and a test page that lets me test it:

```
In recent_posts.html:
{{# recent_posts_1}} 
{{>post_summary}}
{{/recent_posts_1}}

Note: "1" represents the page number, so I can insert any page for test purposes.   I don't expect that the final 
version will require this to be parameterized.
```

I'm looking into the compiler portion now so it auto-generates the /posts/page/1.html pages.  I was thinking something like this in compiler.rb:

```
post_pages = pager.paginate
post_pages.each_value do |p|
    File.open(path, 'w:UTF-8') { |p| p.puts  ?????  }
 end
```

Any suggestions on what to put in the ???? section?    Is there a way to make that 'recent_post.html' into a template and render that via a page object?

I'll keep plugging away at it, but I figured I'd see if you had any suggestions first.

**Comment by jmburges** [comment]
Have you figured this out yet? I'd love to get pagination to work because I think a really long list of blog posts is ridiculous...

**Comment by jasonmtroos** [comment]
Seconding @jmburges's comment -- pagination seems like it ought to have relatively high priority.

**Comment by lynnfaraday** [comment]
I got sidetracked on some other features, but I think I understand the system well enough to finish this now.  I'll put it back on the front burner.

**Comment by plusjade** [comment]
Pagination is finally supported in ruhoh 2.x =)

Docs: http://ruhoh.com/edge/usage/posts/#toc_5 

This will probably change so here's a quick and dirty implementation:

``` html
<h2>Paginated Posts</h2>
{{# posts.paginator }}
<div class="post">
  <h3 class="title"><a href="{{url}}">{{title}}</a> <span class="date">{{ date }}</span></h3>
  {{{ summary }}}
  <div class="more">
    <a href="{{url}}" class="btn">read more..</a>
  </div>
</div>
{{/ posts.paginator }}

<ul>
{{#posts.paginator_navigation}}
  <li>
    {{^is_active_page}}
      <a href="{{url}}">{{name}}</a>
    {{/is_active_page}}

    {{#is_active_page}}
      <a href="{{url}}" style="color:red">{{name}}</a>
    {{/is_active_page}}
  </li>
{{/posts.paginator_navigation}}
</ul>
```
