### ISSUE TITLE
Custom permalink on a per-post basis?

### ISSUE THREAD

**Issue by dph01** [ruhoh/ruhoh.rb#34]
Hi,

I'm guessing this feature isn't already in there, but might be useful for others in the future.

I'm migrating my blog from Posterous to Ruhoh and I'd like to keep the same permalinks. Unfortunately, a couple of the permalinks that Posterous has created seem to be a bit random (like based on a truncated post title), so there's no way that I can configure a site wide permalink convention in Ruhoh that will cover all cases. I'm guessing I'll probably have to get the Ruhoh configuration as close to Posterous' as as possible and then setup redirects on my web-server for the rest (thankfully I've only got a few posts anyway)

How about having the option of setting a custom permalink an a per post basis, as and when required, that overrides the permalink that would otherwise be set by the site convention?

**Comment by plusjade** [comment]
I agree, another member here had the same troubles when migrating from WordPress. It's hard to get the URL's exactly alike so there needs to be more fine-grained control. I'll plan to add manual overrides on a per page basis. The more extensible approach though, would be the ability to overload the way the permalinks are generated in the first place. That way you can create a function that matches, exactly, your existing URL pattern.

**Comment by dph01** [comment]
thanks for adding the feature - it's working well!

**Comment by mudasobwa** [comment]
Since using `:permalink` in every post is a little bit annoying, I would ask if it’s possible to provide some custom metadata field (e. g. `:id`) and then use it in `config.yml`’s permalink section as shown:

```
posts:
  sort: ["date", "desc"]
  permalink: "/post/show/:id"
```

It might be more clear for users. BTW, should not all the metadata fields be propagated to `config.yml` and vise versa?

Thanks in advance.

**Comment by plusjade** [comment]
@mudasobwa good idea, I've implemented it here: https://github.com/ruhoh/ruhoh.rb/commit/f5a9f78a07415c2db0ff08c0e8dbb7955e3681cd  

All metadata is now accessible in the permalink but be careful with `:id` as it's a reserved attribute so you wouldn't be able to define it in the metadata.
