### ISSUE TITLE
Drafts appearing in Archive list 

### ISSUE THREAD

**Issue by alxjrvs** [ruhoh/ruhoh.rb#35]
Hello - unless i am misunderstanding this functionality, the "Archive" page of the site, lists all posts, wether or not they are listed as drafts. It is my expected functionality that any line featuring the "type: draft" line in the head of the file would not be included in this list.

**Comment by plusjade** [comment]
@alxjrvs can you confirm this on your [compiled](http://ruhoh.com/usage/publish/#toc_8) site? 

When running locally (in development), all drafts work as if they were published, as a convenience, so you can see all their tags, categories, urls, meta-data etc.

**Comment by alxjrvs** [comment]
Yup - see, for instance, the difference between [this file](https://github.com/alxjrvs/alxjrvs.ruhoh.com/blob/master/_posts/untitled-0.md) and [this page](http://alxjrvs.ruhoh.com/archive.html) .

**Comment by plusjade** [comment]
good catch. I investigated this on my development branch and see the
error.  ruhoh uses an env flag that gets set to production when compiling.
but I changed the compile script to and its setting the environment _after_
parsing the posts into the database =x

I might push a hotfix for this but id prefer to push my next release in the
next couple of days if I can.  I can paste a rakefile script that will fix
the problem so you can still generate your blog locally if need be. would
that work?

**Comment by alxjrvs** [comment]
That'd be appreciated!

**Comment by plusjade** [comment]
@alxjrvs: Create a file named `Rakefile` in the root of your blog, with this content:

``` ruby
require 'ruhoh'
require 'ruhoh/compiler'

task :compile do
  Ruhoh.setup
  Ruhoh.config.env = 'production'
  Ruhoh::DB.update_all
  Ruhoh::Compiler.compile(ENV['path'])
end
```

Now run:

``` bash
$ rake compile
```

Optionally specify a compile path:

``` bash
$ rake compile path='my-website-path'
```

This fix sets the environment _before_ updating the database.

**Comment by alxjrvs** [comment]
Awesome. Will this work when git pushing to *.ruhoh.com, or will it only effect the local compiled site?

**Comment by plusjade** [comment]
@alxjrvs I just pushed the update so it should work at *.ruhoh.com now. Thanks for reporting this! Feel free to email personally with your usage feedback as well.

EDIT: just test-deployed your blog. Drafts are now properly omitted =)

**Comment by alxjrvs** [comment]
@plusjade Awesome. Happy to be of help - I absolutely will. I am very interested in ruhoh, let me know if you need any help generating use cases or documentation. Marking as closed.
