### ISSUE TITLE
Add content of each post to db.posts.dictionary.<postname>.content

### ISSUE THREAD

**Issue by jfinkels** [ruhoh/ruhoh.rb#38]
Add the content of each post to the payload. This allows the user to create an `index.html` page which lists the content of each post, or perhaps just the first n characters of each post.

**Comment by lynnfaraday** [comment]
See issue #28, #32 and #33 which are all related.

**Comment by plusjade** [comment]
Page content [accessor](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/page.rb#L77-80) and [mustache helper](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/templaters/rmustache.rb#L36-40) added in [ruhoh v.1.0.0.alpha](http://ruhoh.com/blog/releases/version-1-0-0-alpha/).

Your specific use case is documented here: [posts_latest index](https://github.com/ruhoh/blog/blob/master/pages/index.html#L16-26) Let me know how this works for you guys!

See [Configure documentation](http://ruhoh.com/usage/configure/) for configuring posts_latest and summary helpers.

**Note:** Feel free to open new feature-specific issues related to the new posts_latest, summary, and index features. e.g. iterate over specific category, tag, year, or pagination etc.
