### ISSUE TITLE
Not an issue, a suggestion for the usage guide.

### ISSUE THREAD

**Issue by jasonm23** [ruhoh/ruhoh.rb#39]
Serving static HTML with ruby is pretty easy if you do..

```
gem install white_castle
```

Then get yourself in the `_compiled` folder, run..

```
white_castle 
```

Off you go to http://localhost:3000

**Comment by plusjade** [comment]
@jasonm23 thank you! I will test and verify this functionality and then add it into the main website.

**Comment by plusjade** [comment]
@jasonm23 finally got around to updating the docs. Thanks! [view commit](https://github.com/ruhoh/ruhoh.com/commit/9223f30ea4a3ab87744d94c29a45090fbfc7f41b)
