### ISSUE TITLE
Posts with titles with special characters can't be found

### ISSUE THREAD

**Issue by vitorbaptista** [ruhoh/ruhoh.rb#40]
In my dreamhost server, I can't access posts with (). The special case is /, that is not escaped. So, for a title "Do something with /usr blah" becomes "do-something-with-/usr-blah" (2 folders)

I saw that the titles are escaped with CGI::escape. I would suggest to also remove those chars...

**Comment by vitorbaptista** [comment]
P.S.: I'm using Ruhoh 0.3.0.

**Comment by plusjade** [comment]
@vitorbaptista thanks for this report. I have extensively overhauled the way permalinks are generated in [v04.0](https://github.com/ruhoh/ruhoh.rb/commit/75a8a1e495558579bb033f572819f841955fe5af). As you suggest I'm just omitting all special characters and replacing spaces with dashes.

I expect to release the new version this week.

**Comment by mockturtl** [comment]
+1

**Comment by plusjade** [comment]
@vitorbaptista, @mockturtl this should be fixed in [ruhoh v.1.0.0.alpha](http://ruhoh.com/blog/releases/version-1-0-0-alpha/). Rather than CGI escaping special characters we are omitting them. Let me know how it goes. Closes same issue #36

**Comment by mockturtl** [comment]
Fix confirmed.

**Comment by vitorbaptista** [comment]
Thanks! The problem related here doesn't happen anymore, but there's still another one.

As ruhoh doesn't remove the accented characters from the pages URLs, it creates some weird stuff, like www.my-domain.com/diret%C3%B3rio-usr.

I looked quickly at the code, and the fix didn't seemed obvious to me. Mostly because it looks like we're relying that the conversion from title to slug is reversible, which wouldn't be anymore, if this change was made.

What do you think?
