### ISSUE TITLE
mapping a subdomain to my ruhoh.com site

### ISSUE THREAD

**Issue by dph01** [ruhoh/ruhoh.rb#42]
Hi Jade,
I'm wanting to use a CNAME record to point a subdomain (tech.damianhelme.com) my ruhoh site (dph01.ruhoh.com). Is there such a facility in ruhoh to handle this (I've tried and it doesn't work so far).
Thanks
Damian.

**Comment by plusjade** [comment]
Yes, this is a planned feature and one I will be working on next week! https://github.com/ruhoh/post.ruhoh.com/issues/1 I'll make sure to ping you when it's ready.

**Comment by dph01** [comment]
great - that's the last thing I need before I can put my site live.

On Fri, Jun 8, 2012 at 7:14 AM, Jade <
reply@reply.github.com

**Comment by plusjade** [comment]
Custom domain mapping is now officially supported!

Head over to http://post.ruhoh.com, authenticate with GitHub and follow the directions. Let me know if you have any problems and/or feedback. Thanks!

**Comment by kyleroche** [comment]
Can this work w/ teams? Or, would you have time to manually map a custom domain to a team account? I have a team account /m2mio that has a Ruhoh repository. But, all users are associating w/ their own accounts by default. 

Thanks!
