### ISSUE TITLE
Prettify not formatting Scala properly

### ISSUE THREAD

**Issue by dph01** [ruhoh/ruhoh.rb#44]
Prettify doesn't seem to be apply the correct formatting to my Scala code. 

I tried specifying the language explicitly with `<pre class="pretty-print lang-scala">`, but that didn't make a difference.

Here's an example of the problem: http://dph01.ruhoh.com/codetest/ . Not sure what style it's applying, but on Line 3, it's treating everything after the # as a comment.

Anyone else had this problem? Any work-arounds? Is an issue with the prettify code?

**Comment by plusjade** [comment]
Google prettify does document Scala support: http://code.google.com/p/google-code-prettify/source/browse/trunk/src/lang-scala.js so the problem seems to be in the implementation. I'll give this a deeper look as my time permits.

**Comment by dph01** [comment]
Great thanks. It wouldn't stop me from putting the site live, so not
super-urgent.

On Sat, Jun 9, 2012 at 4:02 AM, Jade <
reply@reply.github.com
