### ISSUE TITLE
Got error when install ruhoh

### ISSUE THREAD

**Issue by ikbear** [ruhoh/ruhoh.rb#47]
When install ruhoh, it installs psych, but got this error:

/Users/helishi/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.3.0/psych.bundle: warning: already initialized constant ANY
/Users/helishi/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.3.0/psych.bundle: warning: already initialized constant UTF8
/Users/helishi/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.3.0/psych.bundle: warning: already initialized constant UTF16LE
/Users/helishi/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.3.0/psych.bundle: warning: already initialized constant UTF16BE
/Users/helishi/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.3.0/psych.bundle: warning: already initialized constant ANY
/Users/helishi/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.3.0/psych.bundle: warning: already initialized constant UTF8
/Users/helishi/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.3.0/psych.bundle: warning: already initialized constant UTF16LE
/Users/helishi/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin11.3.0/psych.bundle: warning: already initialized constant UTF16BE

**Comment by jergason** [comment]
Have you tried it in a new RVM gemset?

``` bash
rvm gemset create blog
rvm gemset use blog
gem install ruhoh --version '1.0.0.alpha'
```
