### ISSUE TITLE
Custom Comment Tutorial is Misleading

### ISSUE THREAD

**Issue by lynnfaraday** [ruhoh/ruhoh.rb#49]
I like the new widget structure.  I'm just having a little bit of trouble getting it to work with a custom comments widget.

It seems to be loading the javascript from an unexpected place:

My comments config.yml:

```
javascripts: comments.js
layout : custom
```

This results in the following javascript in the source:

```
<script src="/assets/widgets/comments/javascripts/comments.js?0.4159118015989782"></script>
```

Is it supposed to be under assets?  I was expecting it to be in widgets/javascripts/comments.  Am I missing something?

One other side note:  I think there's a slight mistake in the tutorial.  The image shows the hierarchy as:

```
widgets 
-- comments
-- layouts
```

But I think layouts is supposed to be nested under comments.

Also it shows the filename as being custom_comments.html but it looks like it needs to be named the same as the widget -  in this case comments.html

Thanks.

**Comment by lynnfaraday** [comment]
I figured out the include path, but the tutorial comments are still legit so I'm leaving the issue open and updating the title.

**Comment by plusjade** [comment]
@lynnfaraday hey thanks for the help. Sorry I haven't been updating, but I'm still around. I just started a new job last week so once I settle in I'll be back updating ruhoh! I'll update this thread as soon as I can. Thanks

**Comment by lynnfaraday** [comment]
I understand!  Good luck with the new job :)

**Comment by plusjade** [comment]
@lynnfaraday I've updated the docs in this [commit](https://github.com/ruhoh/ruhoh.com/commit/359d657b5985f41d3136e6a43433131ce7d14783)

Regarding the name `custom_comments.html` so you are right in that the default layout that will be loaded is the layout named exactly the same as the widget. However, in the case of the documentation we are explaining how to define a _custom layout_ rather than a custom widget. It is actually a bit unclear in the docs. Basically defining a custom comments engine is just a matter of defining a _layout_ that loads that particular engine's javascripts. So we aren't actually implementing a new widget, just a new layout for the widget 'comments'. 

Hope that makes sense. Thanks for the feedback and the contributions.

**Comment by plusjade** [comment]
Oh also, regarding the asset path which loads the javascripts. You mentioned you figured it out, but just to go over it again, I am assuming you didn't realize that the paths are not literal paths that map to the directories. I'm using some basic routing that maps some urls to where I need them to go in the file system. `/assets/` becomes a reserved route that maps to both widget and theme based assets.

Was this what you were originally talking about?

**Comment by lynnfaraday** [comment]
@plusjade  - Yes, that was my confusion about assets.  I missed the part about javascripts in the widget config.yml file so my javascripts weren't loading, but I eventually figured it out.

Regarding custom comments:  Perhaps I was doing something wrong, but I became convinced that custom_comments.html _didn't work_.   It was only after I renamed it to comments.html that my custom stuff showed up (apparently for the wrong reason).

**Comment by lynnfaraday** [comment]
@plusjade - I doublechecked.   custom_comments.html doesn't work.   It needs to be custom.html, mirroring the name in the "layout" configuration like disqus.html and livefyre.html    I think the behavior is correct and the documentation just needs to be tweaked.

**Comment by lynnfaraday** [comment]
Actually I just re-read the documentation.  It is correct.  I was just thrown off by the old pre-widget implementation, which used "custom" as the layout name, rather than "custom_comments".   The layout can be anything as long as the layout name and the layout HTML file name match.
