### ISSUE TITLE
realpath

### ISSUE THREAD

**Issue by duplabe** [ruhoh/ruhoh.rb#5]
I installed ruhoh and run ruhoh compile in directory /www/duplabe.hu.  /www is a symlink to /mnt/host. It's a vboxfs shared folder.

Got the following error:

<code>/var/lib/gems/1.8/gems/ruhoh-0.0.3/bin/../lib/ruhoh/utils.rb:23:in `parse_file': 
File not found: /mnt/host/duplabe.hu/mnt/host/duplabe.hu/_templates/themes/twitter/layouts/default.html (RuntimeError)
</code>

**Comment by plusjade** [comment]
@duplabe thank you for these error reports, I don't have a reliable way to test on multiple platforms+environments just yet so this is very helpful.  I think I remember seeing Jekyll disallow symlinks for likely a similar reason.

I'll most likely be documenting how to run a HEAD version of the gem by downloading it from the GitHub repo, that way I don't have to update http://rubygems.org a billion times to fix these issues.

Again, this initial feedback is crucial, thanks =)

**Comment by duplabe** [comment]
Good idea. Looking forward this solution.

Like this enhanced jekyll thing :)
