### ISSUE TITLE
Widgets can't access page data?

### ISSUE THREAD

**Issue by lynnfaraday** [ruhoh/ruhoh.rb#52]
I'm trying to make a custom comments widget that would use the current page url.   In the previous version I could just do {{url}} in the custom_comments partial, but it seems that doesn't work in 1.0.   The widget layout can access config data through {{config}} but not {{page}} or {{url}} or anything like that.

Am I missing something?   Thanks.

**Comment by plusjade** [comment]
You're right, widgets only receive their config data and nothing else. I had originally planned to send in the global payload but it proved to be more difficult than I thought. 

Ultimately I think including the global payload makes sense so it will get done -- I just wanted to ship the minimum viable product!

**Comment by lynnfaraday** [comment]
@plusjade: I understand it's not a priority for the first release - that's cool.  I would really like to get this working for my own widget, though, and I'm happy to do the work myself.  I have modified widgets.rb so that it gets the global payload much like pages do:

```
  def self.payload(widget_config)
      payload = Ruhoh::DB.payload.dup
      payload['config'] = widget_config
      payload
    end
```

Now it has access to all the static database stuff.  What I can't figure out is how to get it the current page context.  I'll keep hammering away at it, but if you can give me any pointers to get started, that'd be great.

**Comment by plusjade** [comment]
Full page context added to widgets at https://github.com/ruhoh/ruhoh.rb/commit/c564232adec56a36a32f723e46dd8b5d48af2126
