### ISSUE TITLE
total post count?

### ISSUE THREAD

**Issue by jacobmgreer** [ruhoh/ruhoh.rb#57]
is there a template tag for total post count?

**Comment by plusjade** [comment]
No, but good idea =)

**Comment by pasindud** [comment]
I am new to ruby but here is something i did user can using by {{{ posts_count }}}

Commit - 5bc3e6bfb390b4a5b07af9956e1d6335bf0fabc9

**Comment by plusjade** [comment]
I'm an idiot. Counting has always been available via Mustache. Assuming you are working with an Array or Hash you can simply call ruby's native `count` or `length` method via Mustache:

ruhoh 1.x

``` html
{{posts.count}}
{{categories.count}}
{{tags.count}}
```

ruhoh 2.x

``` html
{{posts.all.count}}
{{posts.categories.all.count}}
{{posts.tags.all.count}}
```

**Comment by jacobmgreer** [comment]
+1
