### ISSUE TITLE
rss link

### ISSUE THREAD

**Issue by okigan** [ruhoh/ruhoh.rb#58]
Link to rss is not included in a/any page.

Possible modification: 
https://github.com/okigan/blog/commit/415d92e7205c46607f30b8bd10bdc0c8cda7be9c

**Comment by plusjade** [comment]
Good idea, will add it. I stole this from your code:

```
<link rel="alternate" type="application/atom+xml" title="{{ site.title }} Atom feed" href="/rss.xml" />
```

Is this all I need? To be honest I don't know much about rss. Your's work with this tag? If so I'll it in exactly as so - thanks!

**Comment by okigan** [comment]
works for me (tm) in chrome. 

I've sent you a pull request with the above change: 
https://github.com/ruhoh/blog/pull/1

**Comment by plusjade** [comment]
Closing this in favor of tracking this issue on the blog scaffold repo.
