### ISSUE TITLE
Adding scripts to the workflow

### ISSUE THREAD

**Issue by ramnathv** [ruhoh/ruhoh.rb#60]
First off, amazing work with `ruhoh`. I appreciate the amount of thought you have put in, to make things modular and language agnostic. My question is about what is the best way to add external scripts to the workflow.

Let me give you some context. I write my source files in [R Flavored Markdown](http://rstudio.org/docs/authoring/using_markdown), which is a dialect of markdown that supports embedding executable R code inside a markdown document. The workflow I am trying to establish is to use a shell script (which runs my R code) to convert from `Rmd` to `md` and then use `kramdown` to do the conversion of `md` to `html`. 

My question is what is the best way to introduce this into the workflow. Is it a plugin? I am new to `ruby`, so some extra setup instructions would be welcome.

**Comment by plusjade** [comment]
What exactly are you running to parse the R code? Is there no software that converts `rmd` straight to `html` ? 

The best and currently only way to execute any ruby code (and consequently any code by shelling out via ruby) is the plugins. However, the plugins only run on compilation so it won't do any good as far as previewing. 

A lot of ruhoh's users seem to be working with calculation based formatting such as R, mathjax, etc, so I would be very happy to support these features! One small issue is that I don't really understand these implementations =/ 

Anyway, I think the most ideal solution would be for me to support something like [tilt](https://github.com/rtomayko/tilt/) (damn when do this GitHub guys sleep!). Basically tilt lets you do stuff like `myfile.rmd.md.erb.html`   Tilt will go down the chain and do the conversions one after another; quite fantastic! 

However, I initially did not support tilt because the more ruby-centric idioms and packages we use, the less compatible it will be with other languages.

With that said, I'm not about to be blindly stubborn in the face of real-life users actually wanting a nice product. I'll see what I can do!

Any more information on your end would be helpful! Right now, my plan would be to find an `rmd` parser, register it as a tilt converter, then errmm.... refactor ruhoh to support tilt =)

**Comment by ramnathv** [comment]
I am using an R package `knitr` that executes code chunks and converst `Rmd` to `md`. It is possible to convert `Rmd` to `html` within `R`, but I like the flexibility that Ruhoh provides and hence my preferred workflow would be `Rmd -> md` using R and `md -> html` using Ruhoh.

Converting from `Rmd` to `md` is as simple as running `Rscript -e "library(knitr); knit(input, output)"`. So I could just insert this into a ruby script. The question is where do I drop it, and how do I tell ruhoh to execute them in order so that the conversions take place correctly.

**Comment by plusjade** [comment]
@ramnathv  Can you give me a sample `Rmd` file? I'm going to download the knitr stuff and try to execute it locally. That way I'll work out how to integrate it into ruhoh. 

> The question is where do I drop it, and how do I tell ruhoh to execute them in order so that the conversions take place correctly.

By order, you mean parse the formats in the correct order, e.g. `Rmd` -> `md` -> `html` ?

**Comment by ramnathv** [comment]
You will need to install [`R`](http://cran.r-project.org/) and then install `knitr` using `install.packages("knitr")`. Here is a reference to [`R Markdown`](http://rstudio.org/docs/authoring/using_markdown). I can put together a sample `Rmd` file in a gist, but the idea is that `Rmd` files have live R code which get executed and the output inserted to create the `md` file. 

Currently, the way I am doing things is by using a `makefile` with the following commands to handle the conversions

```
SRC      := $(wildcard _src/*.Rmd)
POSTS :=  $(wildcard _posts/*.md)

_posts/%.md: _src/%.Rmd
   Rscript -e 'library(knitr); knit("$<"  "$@")'

site: POSTS
  ruhoh compile
```

I can probably throw this into a rakefile, but maybe there is a better solution.

UPDATE. Here is a link to the `knitr` [stuff](http://yihui.name/knitr/demo/minimal/). Take a look at the GFM example which shows you the input `Rmd` file and the output `md` file

**Comment by ramnathv** [comment]
I would like to revive this thread. I have a function `knit2html` in R that can directly convert a `Rmd` file to `html`. I can make it a command line script. I realize that I can insert it into the plugins architecture as shown below. I have three questions.
1. How do I refer to the path of my script file?
2. Is `content` the file name or the contents of the file? The reason I am asking is because my script file needs to know if the input argument is text or a filename. 
3. Can I just pass the argument `content` to my script as-is?

```
class Ruhoh
  module Converter
    module Markdown
      def self.extensions
        ['.Rmd', '.Rmarkdown']
      end
      def self.convert(content)
        system './knit2html content'
      end
    end
  end
end
```

Resolving this issue will help a lot of `R` bloggers adopt `Ruhoh` as their blogging platform of choice.

**Comment by plusjade** [comment]
@ramnathv the filename (id) is not available to the converters, only the content of the file which is available at `content`.

You can see how it works here: https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/converters/converter.rb

`Ruhoh::Converter.convert(content, id)`  is a wrapper that just looks for a registered converter that is assigned to convert the given `id`'s extension name -- it uses the first one it finds.

Notice also that I downcase all incoming extensions; I do this for basic normalization but it means your Rmd probably won't work (it will look for .rmd).

If you _really_ need to get the `id` (relative filepath) then you can re-implement the converter method:

``` ruby
class Ruhoh
  module Converter

    def self.convert(content, id)
      extension = File.extname(id).downcase

      Ruhoh::Converter.constants.each {|c|
        converter = Ruhoh::Converter.const_get(c)
        next unless converter.respond_to?(:convert)
        next unless converter.respond_to?(:extensions)
        next unless Array(converter.extensions).include?(extension) 
        return converter.convert(content, id) # <----- pass the id along to the converters
      }

      content
    end
end
```

if you do this though then you need to reimplement every converter to expect the id as well. So for example the included .md converter will break, you'll have to use a custom one that does the same thing just adds in the id to the arg list.

Let me know if this makes sense or not. But more importantly, why do you need the id?

**Comment by ramnathv** [comment]
It makes a lot of sense. I can work with the `content` instead of the file id. Now the question is how do I pass content to my script from within the converter. In other words will this work in passing content to my script?

```
system "./knit2html content"
```

**Comment by plusjade** [comment]
well assuming `./knit2html` will take a huge string of content as an argument then you just need to use `content` as a ruby variable:

``` ruby
system("./knit2html", content)
```

**Comment by ramnathv** [comment]
One last question (hopefully). What should be the base path of the script?

**Comment by ramnathv** [comment]
I am still unable to get this working. I moved my script to `/usr/local/bin` so that it is in the global path. I tested it in `irb` and it worked

``` ruby
1.9.2p290 :029 > content = "## this is good"
1.9.2p290 :029 > `knit2html  "#{content}"`
 => "<h2>this is good</h2>\n" 
```

However, when I use it as a plugin, ruhoh hangs. Here is my plugin code

``` ruby
class Ruhoh
  module Converter
    module Knit
      def self.extensions
        ['.rmd', '.rmarkdown']
      end
      def self.convert(content)
        `knit2html  "#{content}"`
      end
    end
  end
end
```

Note that when I replace backticks with a system call, ie `system("knit2html", content)`, compilation works, but instead of the html output, I am just getting `true`, which means the script worked but just returned the wrong output.

Can you help me get this working?

**Comment by plusjade** [comment]
Using `system` won't work because it only returns true/false relative to the success/failure of the call.
Maybe you can try the `%x[]` syntax: http://stackoverflow.com/questions/690151/getting-output-of-system-calls-in-ruby#comment17970623_4278899

Let me know if that works.

**Comment by ramnathv** [comment]
I tried `%x[knit2html "#{content}"]`. It works in `irb` but not inside the plugin. I am not sure why it hangs.

**Comment by plusjade** [comment]
@ramnathv I know you are using [poirot](https://github.com/ramnathv/poirot) now so this particular issue is a not needed for you anymore. Since 2.1 is now released and this issue is now out of sync I'm going to close it.

As I  eventually write some plugins, hopefully I'll have more insight in why system calls were giving us problems.
