### ISSUE TITLE
Per-post summary_line count configuration

### ISSUE THREAD

**Issue by ghost** [ruhoh/ruhoh.rb#64]
It would be nice if the post summary was not a fixed number of lines, but could be specified for each post.

**Comment by plusjade** [comment]
You can specify a custom line-count on the global blog level:

```
#in config.yml
posts :
  summary_lines : 30   # default is 20

```

Are you asking to enable custom summary lines on a per-post basis?

It would be kind of cool to refactor (most) every configuration parameter to cascade from the file level to the global level...

**Comment by ghost** [comment]
Yeah, I meant summary on a per post basis. 

The way you suggested sounds appealing and I guess would be a good policy.
