### ISSUE TITLE
Confused about block mustache helpers

### ISSUE THREAD

**Issue by jmburges** [ruhoh/ruhoh.rb#68]
Hello, 

I'm trying to write a date formatter (Is there a better way to do this?) using the block mustache helpers. Here is my code (in plugins/helpers.rb)

```
  def formatted_date(date)
    newDate = Date.parse(date)
    newDate
  end
```

and I'm using it like this

```
{{#formatted_date }}{{date}}{{/formatted_date}}
```

But I'm getting an error on the parse line saying ArgumentError at /blog invalid date. This makes no sense to me I have copy pasted that date into irb and Date.parse works fine. I have tried stripping all newlines and spaces and it still doesn't work.  Any ideas?

**Comment by plusjade** [comment]
@jmburges this works for me:

```
{{#formatted_date }}
  october
{{/formatted_date}}

# outputs: "2012-10-01"
```

My guess is you have nothing at {{date}} (this is a mustache variable). If you are adding a date in site.yml then it wil be at {{site.date}}

I have to leave right now but try it out and see if you can get it working!

**Comment by jmburges** [comment]
I get the same thing when I put october in as you do. When I put {{date}} back in it then breaks again.

I commented out the other stuff and just printed date back out and it prints correctly. Any ideas? (This is in a partial for posts_list)

**Comment by plusjade** [comment]
Ahh, ok my brain is a little late to the party but I see what is going on now.

So mustache passes in the context _unrendered_ allowing your method to do work on it as needed and/or render it if and when you deem necessary. 

To render the content (that is parse any mustache tags within the current context) just call the render method:

```
def formatted_date(date)
  content = self.render(date)
  newDate = Date.parse(content)
  newDate
end
```

That should do it! Please verify you get this working. Also would be nice to have a link to your public blog and/or github repo =)

**Comment by plusjade** [comment]
> I'm trying to write a date formatter (Is there a better way to do this?) 

I plan to natively support a date format via the config.yml file. Basically input a strftime format and output all dates using the format. However this is not currently a high priority. But it would be along the same lines as you are thinking about in your method, just defined within the gem so its officially supported.

If you have some free time, you might look into integrating your method to support a configuration option. I'll be happy to merge that into the master!
