### ISSUE TITLE
Push does not trigger blog change

### ISSUE THREAD

**Issue by gaoyuan** [ruhoh/ruhoh.rb#71]
I have added webhook.  And the changes can be seen from log.txt. However the pages at gaoyuan.ruhoh.com are not changed.

**Comment by plusjade** [comment]
@gaoyuan is this still a problem for you? I manually triggered the webhook and looks like your blog is up to date relative to your most recent commits. 

Can you verify this is fixed for you? Thanks!

**Comment by gaoyuan** [comment]
Works now. Thanks.

**Comment by plusjade** [comment]
What was the initial problem?

**Comment by gaoyuan** [comment]
Not quite sure. 'cause yesterday when I push to github master, the blog at ruhoh.com is not automatically updated. Yet today it did. :)
