### ISSUE TITLE
Widgets with multiple stylesheets?

### ISSUE THREAD

**Issue by lynnfaraday** [ruhoh/ruhoh.rb#74]
Is it an intentional limitation that widgets can only have one stylesheet, or am I missing something?   I have the workings of a patch, but I wanted to make sure it was actually broken before i submitted it :)

**Comment by plusjade** [comment]
@lynnfaraday currently the widgets can only load one stylesheet. I guess I just assumed a user would specify all the css in one file. What would be the case to use multiple files? Just better organization?

**Comment by lynnfaraday** [comment]
@plusjade - Yeah, that's basically it.   Specifically, I'm making a widget to integrate with [Popeye JQuery](http://dev.herr-schuessler.de/jquery/popeye/), which comes with two stylesheets out of the box.  I could combine them into one, but they're separated for organizational purposes.  [Here's a commit](https://github.com/lynnfaraday/ruhoh.rb/commit/9a426cd28709b3d85fac846cbaa06fe0531f8cbd) to allow multiple stylesheets.

**Comment by plusjade** [comment]
Widgets are now low-priority in favor of building a more integrated plugin system. This is more along the lines of how you want to be able to define ruby methods within widgets. I still don't have a good interface for widgets, but am working on it! =/
