### ISSUE TITLE
initial git push master origin not working w/ ruhoh

### ISSUE THREAD

**Issue by ohNegative** [ruhoh/ruhoh.rb#80]
I cloned the scaffolding on my local but when I went to push this to my repo (which I already created here: https://github.com/ohNegative/ohnegative.ruhoh.com) via command line I keep getting: ERROR Repository not found.

I'm using Windows to do this and can't figure out why I'm getting this error.

Any help would be appreciated.

**Comment by plusjade** [comment]
can you do a `git remote -v` and paste the output here. Also remember your username and repo names are case sensitive so it's probably something to do with the capital N.

**Comment by ohNegative** [comment]
I'll change the capital N and let you know what happens. If it still won't work, I'll paste in the output and we'll go from there. Thanks for your help!

K

**Comment by ohNegative** [comment]
Ok - so that worked. I had to delete the repo and use the correct case-sensitive user name. I just repeated the process and it worked correctly.

Thanks for your help!
