### ISSUE TITLE
Search?

### ISSUE THREAD

**Issue by openpencil** [ruhoh/ruhoh.rb#81]
Hi, I recently started using Ruhoh because it seemed like a very easy way to keep my blog simple and under version control using a linux system. Is there a way I can incorporate a search box into my ruhoh blog?

**Comment by jimjh** [comment]
I don't think there is a way to do that now, but I have plans to work on this feature in the future.

**Comment by plusjade** [comment]
@openpencil, yes the easiest way would be to use a client-side service. There are three I know of:
1. http://www.google.com/cse/
   Uses Google to index your pages then provides an ajax search to display the results without taking the user off your page.
2.  http://www.tipue.com/
   This is a little more more work to setup but unlike Google's CSE, you provide the content to index. This means you don't have to wait for Google to get around to indexing your site and you can control the search results.
3. http://swiftype.com/
   Just out of YC there's also swittype which promises to give you the best of both worlds; search as a service, with fine-grained control of SERP and frequency of index.

I am not sure that ruhoh will or should support a backend type of search considering these client-side options, but it will be based largely on user feedback and expectations.

Please use this thread to document how it goes as I'm sure many users would be appreciative of your experiences in setting this up. Also if you need any help on integrating any of these services with ruhoh, let me know. For example how to provide a json object of tags and/or post content to the service for indexing etc.

**Comment by openpencil** [comment]
@plusjade thanks so very much for your detailed suggestions. I went the _Swiftype_ route and the [the nifty results are on my blog now](http://openpencil.ruhoh.com/).

It couldn't have been easier. I just signed up, hit some straightforward buttons to let the service spider my site and pasted the install code on my default.html page!

**Comment by plusjade** [comment]
Persisting results from this thread in the wiki: https://github.com/ruhoh/ruhoh.rb/wiki/Useful-Tips
