### ISSUE TITLE
git rejects first push

### ISSUE THREAD

**Issue by afknapping** [ruhoh/ruhoh.rb#82]
following the (awesome!) step by step tutorial from scratch i arrived at

```
git push origin master
```

and here is the log:

```
Identity added: /Users/filtercake/.ssh/id_rsa (/Users/filtercake/.ssh/id_rsa)
To git@github.com:filtercake/filtercake.ruhoh.com.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:filtercake/filtercake.ruhoh.com.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

did a `git pull`:

```
warning: no common commits
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
From github.com:filtercake/filtercake.ruhoh.com
 + f69e2b2...72f3fed master     -> origin/master  (forced update)
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by jimjh** [comment]
It seems like there is a conflict between the README file that Github created for you and the README file that came with  Ruhoh. Have you tried the following?

``` bash
git rm README.md
git ci -am 'removed README.md'
git push origin master
```

**Comment by afknapping** [comment]
oh sure, resolved the conflict and it's up and running. just wanted to let you know to (maybe) adjust the tutorial.

**Comment by jimjh** [comment]
Yup.  It might be a good idea to note this in the tutorial.

**Comment by plusjade** [comment]
Can we clarify the use-case here? When would this error occur? Only when the user creates a repository from GitHub website? I'm personally not seeing how GitHub would touch the readme file if I am git cloning a project then pushing it up to a new remote? I haven't tried this myself, just looking to track down the use-case this happens so I can write clear instructions.

**Comment by jimjh** [comment]
When a user creates a repo from the GitHub website, he's given the choice to add a default README file (and so the new repo is not entirely empty.) Therefore, when the user tries to push a ruhoh clone, he will run into a conflict because the ruhoh clone already has a README file.

**Comment by geekhack** [comment]
thanks..helped me big tym.

**Comment by afknapping** [comment]
see https://github.com/ruhoh/ruhoh.com/pull/6
