### ISSUE TITLE
config 404

### ISSUE THREAD

**Issue by afknapping** [ruhoh/ruhoh.rb#83]
http://ruhoh.com/usage/usage/configure

**Comment by plusjade** [comment]
Where is this linked found? It should be http://ruhoh.com/usage/configure

**Comment by afknapping** [comment]
directory structure: http://awesomescreenshot.com/03ddzx38d

**Comment by plusjade** [comment]
[Fixed](https://github.com/ruhoh/ruhoh.com/commit/dc057ee33057e182a32b406230de4d121de5b7de). Great catch -- Thanks!
