### ISSUE TITLE
Ruhoh gem not working properly

### ISSUE THREAD

**Issue by NredYssuts** [ruhoh/ruhoh.rb#89]
I installed ruhoh and it installed with errors, uninstalled, reinstalled and all went fine..
now when i enter the command:

ruhoh help

I receive this:

/Library/Ruby/Gems/1.8/gems/ruhoh-1.1/bin/../lib/ruhoh.rb:2: uninitialized constant Encoding (NameError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Library/Ruby/Gems/1.8/gems/ruhoh-1.1/bin/ruhoh:5
    from /usr/bin/ruhoh:23:in `load'
    from /usr/bin/ruhoh:23

Any ideas?

**Comment by plusjade** [comment]
ruhoh only supports > ruby 1.9.  it looks like you are running ruby 1.8.x.  

```
$ ruby --version
```

what does that say?

**Comment by NredYssuts** [comment]
hmm now I'm completely confused. you're right, I'm using 1.8.3, but when i check through rbenv it returns 1.9.3? any clues as to why?

**Comment by plusjade** [comment]
I don't use rbenv but perhaps you need  to manually specify the ruby you
want to use first? for rvm you can set your default Ruby. is there a way to
do that with rbenv?

**Comment by NredYssuts** [comment]
you can in a way, although this shouldn't matter as I've only installed one version of ruby (although it appears I've installed 2). Since I have a better grasp on the problem I'll try out some things and report back, thanks jade! really love jekyll and ruhoh (but ruhoh a lot more)

**Comment by plusjade** [comment]
most OSes ship with a ruby so your are probably using the OS ruby.  just need to find a way to set default to your new one.

thanks for your support and I hope to get feedback as you continue to use ruhoh!

**Comment by NredYssuts** [comment]
allright, i got rid of rbenv, got rvm, all going well so far and have installed ruhoh successfully although there is one thing I would like to fix.. when i execute "ruhoh help" i get:

RoughThroat-MacBook-Pro:~ nred$ ruhoh help
/Users/nred/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find ruhoh (>= 0) amongst [bundler-1.2.0, rake-0.9.2.2, rubygems-bundler-1.0.7, rubygems-update-1.8.21, rvm-1.11.3.5] (Gem::LoadError)
    from /Users/nred/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/nred/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems.rb:1230:in `gem'
    from /Users/nred/.rvm/rubies/ruby-1.9.2-p320/bin/ruhoh:18:in`<main>'

Although, when i sudo it - "sudo ruhoh help" everything works out fine.. any ideas?

**Comment by jimjh** [comment]
Have you tried:

``` bash
rvm use 1.9.2
gem install ruhoh
```

When you switch ruby versions, you usually need to reinstall gems.

**Comment by NredYssuts** [comment]
yes, currently using ruby-1.9.2-p32 with ruhoh installed ontop.

**Comment by jimjh** [comment]
Hmmm. Just throwing ideas here. Try:

``` bash
gem list --local | grep ruhoh
```

and paste what you see.

**Comment by NredYssuts** [comment]
nothing appears but when I use..

sudo gem list --local | grep ruhoh

I receive

ruhoh 1.1

**Comment by jimjh** [comment]
Yep. Looks like the gem is installed for the superuser, but not for you. Are you able to run

``` bash
gem install ruhoh
```

without `sudo`?

**Comment by NredYssuts** [comment]
no, it tried and fails due to user permissions.. any clue on how i could change this?

**Comment by jimjh** [comment]
This [answer](http://stackoverflow.com/questions/2119064/sudo-gem-install-or-gem-install-and-gem-locations) on StackOverflow might give you more details about the problem you are facing.

**Comment by NredYssuts** [comment]
Thanks for all your help jimjh, I've cleared it up and am happily running ruhoh! :-)
