### ISSUE TITLE
make default extension for new pages configurable

### ISSUE THREAD

**Issue by tkellen** [ruhoh/ruhoh.rb#9]
It's annoying to have to specify a .html extension all the time (for those who don't like/care about markdown).  At the very least publishing an entry should default to the same format as the draft.

**Comment by plusjade** [comment]
Your suggestion is very sensible. Will add this to the feature list:
- Make global default post file extension configurable (will pull from _config.yml)
- Publishing a draft needs to preserve file extension.

Come to think of it that second one is actually a bug. @tkellen thanks for your support and time!

**Comment by tkellen** [comment]
Thank _you_ Jade, I'm really enjoying ruhoh!
