### ISSUE TITLE
/base_path/ setting NOT ignored while previewing

### ISSUE THREAD

**Issue by bartero** [ruhoh/ruhoh.rb#91]
When I set /base_path/ in config.yml, e.g.

```
base_path : '/newblog'
```

and run preview with `rackup` I get

```
RuntimeError at /
Page id not found for url: /
```

Shouldn't this option be ignored while developing?

**Comment by bartero** [comment]
Is it possible to attach a file? I would file the html debug output from the `rackup`

**Comment by afknapping** [comment]
@bartero try pasting the console output into a [gist](https://gist.github.com/).

**Comment by bartero** [comment]
I added a [HTML source and console output](https://gist.github.com/3701768) of the error page output by rackup tool. 

If this is not the most suitable way to share this kind of information, please let me know. 

Cheers,
Bartek

**Comment by plusjade** [comment]
@bartero sorry for the late reply. `base_path` functionality has been overhauled in ruhoh 2.x and should fix your particular bug. To run ruhoh 2.x: https://github.com/ruhoh/blog/tree/2.0.alpha#readme

Thank you for taking the time to document your issue.

**Comment by bartero** [comment]
Thanks for the fix!
