### ISSUE TITLE
list of pages shows "pages" which points to itself

### ISSUE THREAD

**Issue by bijumon** [ruhoh/ruhoh.rb#94]
when showing the list of pages using 

```
{{# pages }}
  {{> pages_list }}
{{/ pages }}
```

a link to itself shows up as "pages"

**Comment by plusjade** [comment]
this is intended as the list is a collection of all available pages.  why wouldn't you want the current page in the list?

**Comment by bijumon** [comment]
because you are already looking at it? it's redundant

**Comment by plusjade** [comment]
Plenty of lists include a self-reference. Navigation, menu bars, etc. "pages" is "all available pages" so this would be a feature, not a bug.

One nice thing you can do with ruhoh is mark/style the current page by checking `is_active_page`. That parameter will automatically be set to `true` for the active page.
