### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [ruhoh/ruhoh.rb#96]
There doesn't appear to be a clear license for ruhoh.rb.

To ease users transitioning from Jekyll, I suggest MIT (or any BSD-alike).

**Comment by plusjade** [comment]
the license is MIT. it says on the ruhoh.com website but not in the actual source I guess! I will look into that thanks!

**Comment by ghost** [comment]
I see that now, thanks. I shall code away in confidence. :)
