### ISSUE TITLE
ruhoh theme command not found

### ISSUE THREAD

**Issue by gwijayas** [ruhoh/ruhoh.rb#99]
After reading the doc at http://ruhoh.com/usage/theming/#toc_12, 

``` bash
$ ruhoh theme 'mytheme'
Command not found

$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]

$ gem list --local|grep ruhoh
ruhoh (1.1)
```

Yes, I've checked with `ruhoh help`, there is no 'theme' commands

**Comment by ramnathv** [comment]
This has been deprecated. Read http://ruhoh.com/latest-updates/

> Theme scaffolding has been removed from the command line tool. `ruhoh theme <name>`
